#!/usr/bin/env python3
"""
مافية عصام - بوت تليجرام للعبة مافيا بلهجة عراقية
Mafia Essam - Telegram Bot for Werewolf/Mafia Game in Iraqi Dialect

Author: Generated by AI
Requirements: python-telegram-bot>=20.0
"""

import os
import random
import logging
import asyncio
import time
import html
import json
import sqlite3
from typing import Dict, List, Optional
from dataclasses import dataclass, field
from enum import Enum

from telegram import (
    Update, InlineKeyboardButton, InlineKeyboardMarkup,
    BotCommand, CallbackQuery
)
from telegram.ext import (
    Application, CommandHandler, CallbackQueryHandler,
    ContextTypes, ConversationHandler, MessageHandler, filters
)

# ============================================================
# CONFIGURATION
# ============================================================

logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    level=logging.INFO
)
logger = logging.getLogger(__name__)

# Get token from environment variable
TOKEN = os.environ.get("BOT_TOKEN")
MEDIA_DIR = os.path.join(os.path.dirname(__file__), "media")
NARRATION_MEMORY_FILE = os.path.join(os.path.dirname(__file__), "used_narration.json")

# ذاكرة دائمة: حتى اللعبة الجاية ما تعيد نفس حچي البوت.
def load_used_narration():
    try:
        with open(NARRATION_MEMORY_FILE, "r", encoding="utf-8") as f:
            return set(json.load(f))
    except Exception:
        return set()

def save_used_narration(items):
    try:
        # نخلي آخر 3000 رسالة حتى الملف ما يكبر بلا حدود.
        data = list(items)[-3000:]
        with open(NARRATION_MEMORY_FILE, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
    except Exception as exc:
        logger.warning("Could not save narration memory: %s", exc)

USED_NARRATION = load_used_narration()


# إحصائيات اللاعبين تنحفظ بقاعدة بيانات SQLite حتى ما تنمسح لو
# السيرفر أعاد التشغيل، وحتى التحديثات تكون آمنة (atomic) بدون
# خطر تلف الملف لو صار انقطاع بمنتصف الكتابة.
STATS_DB_FILE = os.path.join(os.path.dirname(__file__), "player_stats.db")

def get_db_connection():
    conn = sqlite3.connect(STATS_DB_FILE)
    conn.row_factory = sqlite3.Row
    return conn

def init_stats_db():
    conn = get_db_connection()
    try:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS player_stats (
                user_id INTEGER PRIMARY KEY,
                name TEXT NOT NULL DEFAULT '',
                games INTEGER NOT NULL DEFAULT 0,
                wins INTEGER NOT NULL DEFAULT 0,
                losses INTEGER NOT NULL DEFAULT 0,
                votes INTEGER NOT NULL DEFAULT 0
            )
        """)
        conn.commit()
    finally:
        conn.close()

init_stats_db()

def db_get_stats(user_id: int) -> dict:
    conn = get_db_connection()
    try:
        row = conn.execute(
            "SELECT * FROM player_stats WHERE user_id = ?", (user_id,)
        ).fetchone()
        if row:
            return dict(row)
        return {"user_id": user_id, "name": "", "games": 0, "wins": 0, "losses": 0, "votes": 0}
    finally:
        conn.close()

def db_bump(user_id: int, name: str = None, games: int = 0, wins: int = 0, losses: int = 0, votes: int = 0):
    """يزيد قيم الإحصائيات ذرّيًا (atomic upsert)، ويحدّث الاسم إذا انعطى."""
    conn = get_db_connection()
    try:
        conn.execute(
            """
            INSERT INTO player_stats (user_id, name, games, wins, losses, votes)
            VALUES (?, COALESCE(?, ''), ?, ?, ?, ?)
            ON CONFLICT(user_id) DO UPDATE SET
                name = COALESCE(excluded.name, player_stats.name),
                games = player_stats.games + excluded.games,
                wins = player_stats.wins + excluded.wins,
                losses = player_stats.losses + excluded.losses,
                votes = player_stats.votes + excluded.votes
            """,
            (user_id, name, games, wins, losses, votes),
        )
        conn.commit()
    finally:
        conn.close()

def db_get_leaderboard(limit: int = 10):
    conn = get_db_connection()
    try:
        rows = conn.execute(
            "SELECT * FROM player_stats WHERE games > 0 ORDER BY wins DESC, games DESC LIMIT ?",
            (limit,),
        ).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()



# الفيديوهات موزعة حسب الحالة فقط:
# بداية اللعبة = القمر، الحريق = مضرم الحرائق، السكين = السفاح.
EVENT_EFFECTS = {
    "game_start": "game_start_moon.mp4",
    "arsonist_burn": "arsonist_burn.mp4",
    "serial_killer_attack": "serial_killer_attack.mp4",
}


async def send_arsonist_burn_effect(bot, chat_id: int):
    """تأثير الحريق، مخصص حصراً لمضرم الحرائق لما يحرق البيت."""
    return await send_effect(bot, chat_id, EVENT_EFFECTS["arsonist_burn"], "🔥🏠 مضرم الحرائق ولّع البيت!")


async def send_serial_killer_effect(bot, chat_id: int):
    """تأثير السكين، مخصص حصراً لهجوم السفاح."""
    return await send_effect(bot, chat_id, EVENT_EFFECTS["serial_killer_attack"], "🔪 السفاح ضرب ضربته!")


async def send_effect(bot, chat_id: int, filename: str, caption: str = None):
    """Send a short local MP4 effect; silently fall back if the media is unavailable."""
    path = os.path.join(MEDIA_DIR, filename)
    if not os.path.isfile(path):
        return False
    try:
        with open(path, "rb") as video:
            await bot.send_video(
                chat_id=chat_id,
                video=video,
                caption=caption,
                supports_streaming=True,
            )
        return True
    except Exception as exc:
        logger.warning("Could not send effect %s to %s: %s", filename, chat_id, exc)
        return False

async def send_random_effect(bot, chat_id: int, filenames, caption: str = None):
    """Pick one local effect at random from the supplied event-specific files."""
    available = [name for name in filenames if os.path.isfile(os.path.join(MEDIA_DIR, name))]
    if not available:
        return False
    return await send_effect(bot, chat_id, random.choice(available), caption)


# ============================================================
# IRAQI MESSAGES - بهجة عراقية خالصة
# ============================================================

MSG = {
    "welcome": """
🐺 *هلا فيك في بوت مافية الذئب* 🇮🇶

*شلون تلعب؟*
1️⃣ تريد تسوي لعبة جديدة؟ اكتب /newgame
2️⃣ من تنفتح اللعبة دوس زر *يلا دوس انضمام*
3️⃣ من يكتمل العدد، صاحب اللعبة يكتب /startgame

*أقل شي:* 5 لاعبين | *أكثر شي:* 20 لاعب

_يلا شبيك؟ ادخل ويانه وخلي نشوف منو يطلع ذيب 😂🐺_
""",
    "game_created": """
🎮 *يلااا انفتحت لعبة جديدة!*

صاحب اللعبة: {host_name}
كود اللعبة: `{game_id}`

اللاعبين ({count}/{max_players}):
{players_list}

👇 اللي يريد يدخل، بس دوس الزر جوه
⏳ *باقي على الانضمام: {seconds} ثانية*
""",
    "joined": """
✅ *هلا {name}، دخلت ويانه!*

عدد اللاعبين هسة: {count}/{max}
{players_list}

{hint}
""",
    "already_joined": "يا {name}، إنت داخل من قبل يمعود 😂",
    "game_full": "اللعبة امتلت يمعود 😂 انتظر الجولة الجاية.",
    "no_game": "ماكو لعبة شغالة هسة! سوّوا وحدة بـ /newgame",
    "not_host": "يا {name}، بس صاحب اللعبة يگدر يبديها 😅",
    "game_starting": """
🌙 *يلااا بدت اللعبة!* 🐺

هسة راح نوزع الأدوار... انتظروا شوي 🤫
""",
    "role_assigned": """
🎭 *دورك: {role_name}*

{role_description}

{abilities}

*لا تفضح دورك يمعود!* خليها سر بيناتنا 🤫
""",
    "night_falls": """
🌙 *حل الليل...*

الكل نام، بس أكو ناس هسة راح تشتغل 😈

{actions}
""",
    "wolf_prompt": """
🐺 *إنت ذيب!*

اختار منو تريدون تاكلون الليلة:
{targets}

{timer_warning}
""",
    "seer_prompt": """
🔮 *إنت العرّاف!*

اختار واحد حتى تعرف شنو دوره:
{targets}
""",
    "healer_prompt": """
⚕️ *إنت الحكيم!*

اختار واحد تريد تحميه هالليلة:
{targets}
""",
    "sk_prompt": """
🔪 *إنت السفاح!*

اختار ضحيتك الليلة (حمايه الحكيم ما تنفعهم منك):
{targets}
""",
    "arsonist_prompt": """
🔥 *إنت مضرم الحرائق!*

ترش لاعب بالبنزين، أو تولّع كل اللي رشيتهم من قبل دفعة وحدة:
{targets}
{ignite_option}
""",
    "seer_result": """
🔮 *طلعت النتيجة:*

{name} → {result}

{comment}
""",
    "morning_arrives": """
☀️ *طلع الصبح!*

{death_message}

*اللي بعدهم عايشين ({alive_count}):*
{alive_list}

{discussion_prompt}
""",
    "no_death": """
☀️ *طلع الصبح!*

الحمدلله، هالليلة ما مات أحد! 🙏
شكله الحكيم لحق وأنقذ واحد 😎

*اللي بعدهم عايشين ({alive_count}):*
{alive_list}
""",
    "death_announcement": """
💀 *يا ساتر!* 💀

هالليلة {name} ({role}) {cause}

_الله يرحمه... الذئاب ما تعرف الرحمة 😂🐺_
""",
    "discussion_time": """
💬 *هسة وقت الحچي!* 💬

يلا منو تشكون بيه؟ كل واحد يحچي ويدافع عن روحه 😂

⏰ *عندكم {seconds} ثانية*

وبعدين نروح للتصويت! 🗳️
""",
    "voting_time": """
🗳️ *هسة وقت التصويت!*

كل واحد يروح لخاص البوت ويختار منو يصوّت عليه.
التصويت **سري** - محد يعرف منو صوّت على منو لين تخلص الفترة! 🤫

⏰ *عندكم 60 ثانية*
""",
    "vote_private": "🗳️ اختار منو تريد تصوّت عليه:",
    "vote_cast": "✅ تم، صوتك انحسب!",
    "already_voted": "يا {name}، إنت مصوّت من قبل 😂 ما يصير مرتين!",
    "elimination_result": """
⚔️ *خلص التصويت!*

👤 *المتهم: {accused_name}*

{eliminated_message}
""",
    "player_eliminated": """
💀 *{name} طلع من اللعبة!* 💀

دوره الحقيقي: *{role}*

{name} {comment}
""",
    "tie_vote": """
🤝 *صار تعادل!*

{names} طلع عدهم نفس عدد الأصوات!

هالمرة محد ينطرد... بس انتبهوا للجولة الجاية 😂
""",
    "wolves_win": """
🐺 *الذيب فاز باللعبة!* 🔥

🏆 *الذئاب الفايزين:*
{wolves_list}

{taunt}
""",
    "village_win": """
🏆 *أهل القرية فازوا!* 🎉

🛡️ *اللي ظلوا عايشين:*
{survivors_list}

{celebration}
""",
    "outcast_win": """
🃏 *المنبوذ فاز وحده!* 😂

{name} ظل للنهاية وسواها!

خوش لعب يمعود 😎🔥
""",
    "serial_killer_win": """
🔪 *السفاح فاز وحده!* 😱

{name} ذبحهم كلهم وظل واقف!

عمرك ما تشك بالساكت 😈🔪
""",
    "arsonist_win": """
🔥 *مضرم الحرائق فاز وحده!* 🔥

{name} ولّع الكل وظل الوحيد الحي!

😂 هذا اللي يريد يشوف العالم يحترق!
""",
    "fool_win": """
🤡 *الأخرق فاز!* 😂😂😂

{name} كان الأخرق طول الوقت، وأنتوا طردتوه بأيديكم!

خدعكم بذكاء - اللعبة خلصت هسة والفوز إله لحاله! 🏆🤡
""",
    "bomb_explosion": """
💣 *بووووم!* 💥

{bomber} كان البداغ! لمن طردتوه، انفجر وأخذ {victim} وياه للقبر!

😱 اللي شكوا بيه دفعوا ثمنها وحدة زيادة!
""",
    "wolf_taunts": [
        "😂 الذئاب سووها وبلعوا القرية كلها!",
        "😈 أهل القرية شكد حاولوا... بس الذيب لعبها صح!",
        "🐺 عصام عمكم بس 😎🔥",
    ],
    "village_celebrations": [
        "😂 خوش لعب! كشفوهم قبل لا يبلعونكم.",
        "🧠 لعبتوها صح، الذئاب ما لگوا مخرج.",
        "🇮🇶 خوش شغل يا أهل القرية!",
    ],
    "game_ended": "🛑 خلصت اللعبة! إذا تريدون لعبة جديدة اكتبوا /newgame",
    "game_reset": "✅ رجعناها من جديد! هسة اكتبوا /newgame",
    "not_in_game": "يا {name}، إنت مو داخل بهاللعبة يمعود.",
    "help": """
📜 *أوامر بوت مافية الذئب:*

/newgame - تسوي لعبة جديدة
/startgame - تبدي اللعبة
/startchaos - تبدي وضع الفوضى
/extend - تزيد أو تقلل مهلة الانضمام
/players - تشوف منو داخل
/flee - تطلع من اللعبة
/nextgame - ينبهك بالخاص للجولة الجاية
/stats - إحصائياتك
/ping - يفحص سرعة البوت
/chatid - يطلع آيدي الكروب
/version - نسخة البوت
/runinfo - معلومات التشغيل
/config - إعدادات الجلسة
/forcestart - يبدي اللعبة بالقوة
/endgame - يخلص اللعبة
/rules - القوانين
/help - هاي القائمة

*ملاحظة:* الدخول يصير من زر *يلا دوس انضمام*، مو بأمر كتابة.
""",
    "rules": """
📋 *قوانين اللعبة:*

*شلون يفوزون؟*
🐺 الذئاب: ياكلون الباقين لحد ما يصير عددهم مثلهم أو أكثر.
🛡️ أهل القرية: يكشفون الذئاب ويطلعوهم من اللعبة.

*الأدوار:*
🐺 *الذيب* - بالليل يختار ضحية
🔮 *العرّاف* - يعرف دور لاعب
⚕️ *الحكيم* - يحمي لاعب من الهجوم
⚖️ *المحامي* - ينقذ لاعب من الطرد مرة وحدة
🃏 *المنبوذ* - يريد يبقى وحده بالنهاية
🔪 *السفاح* - يقتل لحاله كل ليلة، حمايه الحكيم ما تنفع ضده
🔥 *مضرم الحرائق* - يرش لاعبين بالبنزين ويولّعهم دفعة وحدة
🤡 *الأخرق* - يفوز لو القرية طردته بالتصويت (مو لو الذئاب قتلوه)
💣 *البداغ* - لو انطرد بالتصويت، يفجّر ويأخذ لاعب ثاني وياه

*مراحل اللعبة:*
1️⃣ بالليل: كل صاحب دور يسوي شغلته
2️⃣ بالصبح: نعرف شصار
3️⃣ الحچي: الكل يتهم ويدافع عن روحه
4️⃣ التصويت: تختارون منو يطلع
5️⃣ ونبقى نعيد لحد ما يفوز فريق

*لا تفضح دورك بالخاص، خلي اللعب حماس 😂*
""",
}

# ============================================================
# ROLES DATA
# ============================================================

ROLES = {
    "wolf": {
        "name": "🐺 الذيب",
        "team": "wolves",
        "description": "إنت ويا فريق الذئاب! 🐺\n"
                      "كل ليلة تگعدون وتختارون واحد.\n"
                      "هدفكم تاكلون الباقين لحد ما يصير عددكم كدهم أو أكثر!",
        "abilities": "🗡️ تختارون ضحية كل ليلة\n"
                    "👁️ تعرف باقي الذئاب من البداية\n"
                    "🎭 تگدر تخدع الباقين بالحچي",
    },
    "civilian": {
        "name": "🛡️ المدني",
        "team": "village",
        "description": "إنت مدني بريء! 🛡️\n"
                      "ما عندك قدرة خاصة، بس مخك وحسك يكفون.\n"
                      "دور على الذئاب وصوّت عليهم!",
        "abilities": "🧠 استخدم مخك حتى تكشف الذئاب\n"
                    "💬 احچي وناقش وصوّت\n"
                    "🗳️ صوتك يفرق مثل الباقين!",
    },
    "seer": {
        "name": "🔮 العرّاف",
        "team": "village",
        "description": "إنت العرّاف! 🔮\n"
                      "كل ليلة تگدر تعرف دور واحد.\n"
                      "بس لا تفضح نفسك للذئاب!",
        "abilities": "🔍 تعرف دور لاعب واحد كل ليلة\n"
                    "👁️ تعرف إذا اللاعب ذيب لو لا\n"
                    "⚠️ الذئاب يحبون يخلصون منك بسرعة!",
    },
    "healer": {
        "name": "⚕️ الحكيم",
        "team": "village",
        "description": "إنت الحكيم! ⚕️\n"
                      "كل ليلة تگدر تحمي واحد من الذئاب.\n"
                      "بس ما تگدر تحمي نفسك ليلتين ورا بعض!",
        "abilities": "🛡️ تحمي لاعب من هجوم الذئاب كل ليلة\n"
                    "🚫 ما تگدر تحمي نفسك مرتين ورا بعض\n"
                    "💪 حمايتك ممكن تنقذ واحد!",
    },
    "lawyer": {
        "name": "⚖️ المحامي",
        "team": "village",
        "description": "إنت المحامي! ⚖️\n"
                      "تگدر تنقذ لاعب من الطرد مرة وحدة بس باللعبة!",
        "abilities": "🛡️ تدافع عن لاعب من الطرد (مرة وحدة)\n"
                    "💼 دفاعك ينقذه حتى لو الأصوات عليه أكثر",
    },
    "outcast": {
        "name": "🃏 المنبوذ",
        "team": "outcast",
        "description": "إنت المنبوذ! 🃏\n"
                      "مو ويا الذئاب ولا ويا القرية.\n"
                      "كل همك تبقى وحدك بالنهاية!",
        "abilities": "🎯 تفوز إذا بقيت للنهاية وحدك\n"
                    "🤫 مو مهم منو يفوز، المهم تبقى عايش!\n"
                    "🎭 لخبطهم كلهم وخليك متخفي!",
    },
    "serial_killer": {
        "name": "🔪 السفاح",
        "team": "serial_killer",
        "description": "إنت السفاح! 🔪\n"
                      "لا ويا الذئاب ولا ويا القرية، تلعب لحالك.\n"
                      "كل ليلة تگدر تذبح واحد، وحمايه الحكيم ما توگف عليك!",
        "abilities": "🔪 تقتل لاعب واحد كل ليلة (حمايه الحكيم ما تشتغل ضدك)\n"
                    "🎯 تفوز إذا بقيت الوحيد الحي بالساحة\n"
                    "🤫 خل الكل يشك بالذئاب مو بيك!",
    },
    "arsonist": {
        "name": "🔥 مضرم الحرائق",
        "team": "arsonist",
        "description": "إنت مضرم الحرائق! 🔥\n"
                      "تلعب لحالك. كل ليلة تگدر ترش لاعب بالبنزين،\n"
                      "وبأي وقت تگدر تولّع كل المرشوشين دفعة وحدة!",
        "abilities": "⛽ ترش لاعب بالبنزين كل ليلة (ما يحس بيها)\n"
                    "🔥 تگدر تولّع كل المرشوشين بأي ليلة تختارها\n"
                    "🎯 تفوز إذا بقيت الوحيد الحي بالساحة",
    },
    "fool": {
        "name": "🤡 الأخرق",
        "team": "village",
        "description": "إنت الأخرق! 🤡\n"
                      "لعبتك عكسية: لو القرية طردتك بالتصويت، إنت الفايز!\n"
                      "بس لو الذئاب قتلوك بالليل، خسرت مثل أي واحد ثاني.",
        "abilities": "🎭 تصرف بغرابة، خلي القرية تشك بيك وتطردك\n"
                    "🏆 تفوز بس لو انطردت بالتصويت - مو لو انقتلت بالليل",
    },
    "bomber": {
        "name": "💣 البداغ",
        "team": "village",
        "description": "إنت البداغ! 💣\n"
                      "لو القرية طردتك بالتصويت، تنفجر وتاخذ وحد ثاني وياك للقبر!\n"
                      "لو الذئاب قتلوك بالليل، تموت عادي بدون انفجار.",
        "abilities": "💥 لو انطردت بالتصويت، لاعب عشوائي ثاني يموت وياك\n"
                    "🎯 خلي القرية تحسبها مرتين گبل لا تصوت عليك!",
    },
}

# ============================================================
# GAME STATE
# ============================================================

class GamePhase(Enum):
    WAITING = "waiting"
    NIGHT = "night"
    SEER = "seer"
    HEALER = "healer"
    WOLF = "wolf"
    SERIAL_KILLER = "serial_killer"
    ARSONIST = "arsonist"
    MORNING = "morning"
    DISCUSSION = "discussion"
    VOTING = "voting"
    ELIMINATION = "elimination"
    ENDED = "ended"


@dataclass
class Player:
    user_id: int
    name: str
    role: str = ""
    team: str = ""
    alive: bool = True
    protected_by_healer: bool = False
    protected_by_lawyer: bool = False
    has_used_lawyer: bool = False


@dataclass
class GameSession:
    game_id: str
    host_id: int
    host_name: str
    players: Dict[int, Player] = field(default_factory=dict)
    phase: GamePhase = GamePhase.WAITING
    round_num: int = 0
    last_protected: int = None
    night_kills: List[int] = field(default_factory=list)
    votes: Dict[int, int] = field(default_factory=dict)
    wolf_chat_id: int = None
    chat_id: int = None
    chaos_mode: bool = False
    join_deadline: float = None
    join_task: object = None
    narration_used: set = field(default_factory=set)
    discussion_events: List[str] = field(default_factory=list)
    arsonist_doused: set = field(default_factory=set)
    lock: object = field(default_factory=asyncio.Lock)


# ============================================================
# GLOBAL GAMES STORE
# ============================================================

games: Dict[str, GameSession] = {}
user_games: Dict[int, str] = {}  # user_id -> game_id

# نافذة "آخر كلمة" - chat_id -> user_id اللي إله الفرصة يحچي آخر كلمة گبل ما ينكشف دوره.
# نفس رسالة النص العادية اللي يرسلها هذا اللاعب بهاي الفترة تنلتقط وتترد بأسلوب درامي.
LAST_WORDS_WINDOW: Dict[int, int] = {}
nextgame_subscribers: set[int] = set()
# ملاحظة: إحصائيات اللاعبين صارت تنقرى/تنكتب مباشرة من قاعدة بيانات
# SQLite (شوف db_get_stats / db_bump / db_get_leaderboard فوق) بدل
# القاموس بالذاكرة، حتى تكون كل عملية تحديث آمنة وذرّية.


# ============================================================
# UTILITY FUNCTIONS
# ============================================================

def get_random_taunt(taunts_list):
    return random.choice(taunts_list)


async def record_game_result(game: "GameSession", winning_team: str):
    """يحدّث إحصائيات الفوز/الخسارة لكل لاعب بعد نهاية اللعبة (كتابة ذرّية بقاعدة البيانات، بخيط منفصل حتى ما توگف حلقة الأحداث)."""
    for uid, p in game.players.items():
        if p.team == winning_team:
            await asyncio.to_thread(db_bump, uid, p.name, 0, 1, 0, 0)
        else:
            await asyncio.to_thread(db_bump, uid, p.name, 0, 0, 1, 0)


def generate_game_id():
    return str(random.randint(10000, 99999))


def get_role_emoji(role):
    emojis = {
        "wolf": "🐺",
        "civilian": "🛡️",
        "seer": "🔮",
        "healer": "⚕️",
        "lawyer": "⚖️",
        "outcast": "🃏",
        "serial_killer": "🔪",
        "arsonist": "🔥",
        "fool": "🤡",
        "bomber": "💣",
    }
    return emojis.get(role, "❓")


def get_player_list_text(players_dict, show_roles=False):
    lines = []
    for i, (uid, p) in enumerate(players_dict.items(), 1):
        status = "🟢" if p.alive else "💀"
        if show_roles:
            lines.append(f"{i}. {status} {p.name} - {ROLES[p.role]['name']}")
        else:
            lines.append(f"{i}. {status} {p.name}")
    return "\n".join(lines) if lines else "*ماكو لاعبين هسة*"


def assign_roles(num_players):
    """Assign roles based on number of players"""
    if num_players < 5:
        return None
    
    roles = []
    
    # Always have these
    roles.extend(["wolf", "seer", "healer"])
    
    if num_players >= 6:
        roles.append("wolf")
    if num_players >= 7:
        roles.append("lawyer")
    if num_players >= 8:
        roles.append("outcast")
    if num_players >= 9:
        roles.append("fool")
    if num_players >= 10:
        roles.append("wolf")
    if num_players >= 11:
        roles.append("lawyer")
    if num_players >= 12:
        roles.append("serial_killer")
    if num_players >= 13:
        roles.append("wolf")
    if num_players >= 14:
        roles.append("bomber")
    if num_players >= 15:
        roles.append("arsonist")
    if num_players >= 16:
        roles.append("wolf")
    if num_players >= 18:
        roles.append("seer")
    
    # Fill rest with civilians
    while len(roles) < num_players:
        roles.append("civilian")
    
    random.shuffle(roles)
    return roles


# ============================================================
# SMART IRAQI NARRATOR - راوي ذكي بدون تكرار
# ============================================================
NARRATION_BANK = {
    "discussion_open": [
        "💬 هسة الحچي جد، لا أحد يختفي ورا الصمت.",
        "🕵️ خل نشوف، منو عنده تفسير ومنو دا يلف ويدور؟",
        "👀 كل كلمة تنحسب هسة، لا أحد يفلتها بسهولة.",
        "🔥 يلا افتحوا السالفة، الشك وحده ما يطلع ذيب.",
        "😏 اليوم كل واحد يدافع عن روحه، والساكت عليه ألف علامة استفهام.",
    ],
    "discussion_nudge": [
        "🤨 واحد منكم دا يعرف أكثر من اللي دا يكوله، بس منو؟",
        "👂 سمعتوا الحچي زين؟ أكو تناقضات لو بس آني حاس بيها؟",
        "🧐 لا تبلعون أول تهمة، اربطوا كلامكم باللي صار.",
        "😈 إذا الذئب بينكم، أكيد هسة مرتاح لأنكم متفقين على شي غلط.",
        "🗣️ يلا، اللي عنده دليل يطلعه، واللي عنده شك يشرح شنو سببه.",
        "😂 لا تحولون النقاش لسوالف، الوقت دا يركض.",
        "👀 فلان ساكت؟ هذا مو دليل، بس هم مو شي نتجاهله.",
        "⚖️ ركزوا: منو غير كلامه من أول اتهام لهسة؟",
    ],
    "late_discussion": [
        "⏳ ما بقى هواي، ثبتوا شكوككم قبل لا يجي التصويت.",
        "🔥 آخر فرصة للحچي، بعد شوي كل واحد يتحمل صوته.",
        "🗳️ جهزوا قراركم، لأن الخطأ هالمرة ممكن يغيّر اللعبة كلها.",
        "😬 لا أحد يكول بعدين ما لحكت أحچي، هسة وقتها.",
    ],
    "after_death": [
        "💀 الموت مو بس خسارة، أحيانًا هو أول خيط يفضح الباقين.",
        "🐺 من المستفيد من اختفاء هذا اللاعب؟ هذا السؤال أهم من الصراخ.",
        "🔍 ركزوا على آخر حچي گاله قبل لا يطلع من اللعبة.",
        "😶 هالموت يغيّر حسابات هواي ناس، انتبهوا لمن تبدل أسلوبه فجأة.",
    ],
    "after_save": [
        "🛡️ أحدهم نجا الليلة، والذئاب هسة يعرفون إن الطريق مو مفتوح إلهم.",
        "😏 محاولة فشلت، بس منو كان الهدف؟ يمكن الحچي يكشف شي.",
        "🌤️ النجاة الليلة راح تخلّي الشك ينتقل لمكان ثاني.",
    ],
    # مشاهد سينمائية متغيرة لموت الذئب - كل ليلة قصة مختلفة، بلا تكرار
    "wolf_kill_scene": [
        "بينما يستيقظ الجميع بالصباح، يشمون رائحةً مريعة. يتبعون الرائحة ليعثروا على {name} ممزقًا إلى أشلاء بالحظيرة، ورأسه مفقود. 🩸",
        "صوت نباح بعيد أيقظ القرية فجرًا. لمن ركضوا نحو البير، لگوا {name} طايف بيه، وآثار مخالب على رگبته. 🐾",
        "الثلج تحت الشجرة العتيگة كان أحمر بالكامل. {name} ما بقى منه غير ملابسه الممزقة وبقايا دم طازج. ❄️🩸",
        "سمعوا صرخة بمنتصف الليل، بس محد جرأ يطلع. بالصبح لگوا {name} متروك عند باب الجامع، وجسمه مليان جروح عميقة. 😱",
        "الكلاب ما وگفت تنبح طول الليل. بالصبح عرفوا ليش - {name} كان مرمي بالساحية، والذيب ما ترك منه شي يذكر. 🌊",
        "رائحة الدم اجتذبت الكل نحو المطحنة القديمة. {name} كان معلّق هناك، والعلامات على جسمه تكول إن الذيب ما رحمه أبدًا. ⚙️🩸",
    ],
    # مشاهد سينمائية للسفاح - أسلوب مختلف كليًا عن الذئب (سكين، بهدوء)
    "sk_kill_scene": [
        "ماكو دم على الأرض، بس {name} انلگى بغرفته وهو ميت بسكتة تامة، وسكين مغروزة بمكانها بدقة غريبة. 🔪",
        "الباب كان مقفول من الداخل، بس {name} انلگى مذبوح بهدوء تام، وكأن شخص عرف بالضبط وين يضرب. 🗝️🔪",
        "محد سمع صراخ ولا حتى همسة. {name} انلگى بكرسيه، ونظرة الصدمة بعده على وجهه. الهدوء كان جزء من الجريمة. 😶🔪",
    ],
    # مشاهد سينمائية لمضرم الحرائق
    "arsonist_kill_scene": [
        "رائحة البنزين وصلت گبل النار. لمن اطفوا الحريق، ما بقى من {name} غير رماد وبقايا محروقة تحت أنقاض البيت. 🔥🏚️",
        "شعلة النار طلعت فجأة من العدم، وحاصرت {name} بلا مهرب. الصبح، الگرية كلها تشم رائحة الحريق. 🔥",
    ],
    # جمل تأكيد عشوائية عند استخدام كل قدرة - كل مرة كلام مختلف
    "wolf_confirm": [
        "✅ خوش اختيار يا ذيب، اللحم طري 🐺",
        "🩸 الفريسة تحددت، الليلة راح تكون دموية",
        "🐾 اختيار ذكي، خلي الباقين يتخبطون بالصبح",
        "😈 القرار انحسم، هسة بس ننطر الصبح",
    ],
    "seer_confirm": [
        "🔮 الرؤية وضحت... خزن هالمعلومة زين",
        "👁️ الغيب انكشف شوية، استخدمها بذكاء",
        "🌙 عرفت الحقيقة، بس خلها سر لين الوقت المناسب",
    ],
    "healer_confirm": [
        "⚕️ الدعوة انرفعت، الحماية بيد الله",
        "🛡️ اخترت تحمي، خلي القدر يسوي الباقي",
        "🙏 يارب تكون اخترت صح، الليلة حرجة",
    ],
    "sk_confirm": [
        "🔪 الهدف تحدد، الليلة راح يصير سكوت تام",
        "😏 اختيار بارد الأعصاب، ماكو رحمة الليلة",
        "🗡️ القرار انحسم بصمت، مثل ما يحب السفاح",
    ],
    "arsonist_confirm_douse": [
        "⛽ رشيته زين، بانتظار الوليعة الكبيرة",
        "🔥 خطوة أولى للحريق، صبر شوي",
        "😈 البنزين انصب، والنار جاية بوقتها",
    ],
    # جمل افتتاحية سردية لكل دور - كل ليلة صياغة مختلفة (مثل رواية)، بدل
    # نفس الجملة الثابتة كل مرة. تنسحب بلا تكرار زي بقية بنك الجمل.
    "healer_intro": [
        "⚕️ الليل ينزل، وبيدك دواء وحماية. منو تختار تحرسه هالليلة؟",
        "⚕️ القرية نايمة وما تدري شنو ينطرها. عينك على منو الليلة؟",
        "⚕️ خطواتك الهادية تروح بين البيوت. وين تحط درعك الليلة؟",
        "⚕️ الظلام يخبي كل شي إلا نيتك بالحماية. منو المحظوظ الليلة؟",
    ],
    "seer_intro": [
        "🔮 الكرة تلمع بيدك، والغيب يناديك. منو تريد تكشف حقيقته؟",
        "🔮 السكون يحيط بيك وأنت تركز على الرؤية. وين توجه نظرك الليلة؟",
        "🔮 الظلام يفتح لك باب المعرفة. منو الاسم اللي بيدور براسك؟",
        "🔮 عيونك تشوف اللي ما يشوفه غيرك. منو تختار تفحصه هالليلة؟",
    ],
    "wolf_intro": [
        "🐺 القطيع مجتمع بالظلام، والجوع يسيطر عليكم. منو الفريسة الليلة؟",
        "🐺 عيونكم تلمع بالعتمة وأنتوا تراقبون القرية النايمة. منو الهدف؟",
        "🐺 الليل إلكم، والقرار قراركم. اتفقوا وياهم على الضحية.",
        "🐺 رائحة الخوف تملأ الهوا، وأنتوا جاهزين. منو يصير الفريسة؟",
    ],
    "sk_intro": [
        "🔪 وحدك بالظلام، وسكينك جاهزة. منو الاسم على قائمتك الليلة؟",
        "🔪 محد يعرف بوجودك بينهم. اختار بهدوء - منو الضحية؟",
        "🔪 القطيع يشك بالذئاب، وأنت الخطر الحقيقي المختفي. منو دورك عليه؟",
        "🔪 خطواتك بلا صوت، ونيتك واضحة. منو تختار الليلة؟",
    ],
    "arsonist_intro": [
        "🔥 قنينة البنزين بيدك، وخطة الحريق تكبر براسك. منو ترش أو تولّع؟",
        "🔥 رائحة الوقود تسبقك بالظلام. شنو خطوتك الليلة؟",
        "🔥 كل بيت رشيته هو خطوة أقرب للحريق الكبير. شنو تسوي الليلة؟",
        "🔥 عود الثقاب جاهز بجيبك. تولّع هسة، أو تصبر وترش أكثر؟",
    ],
    "lawyer_intro": [
        "⚖️ ملفاتك جاهزة، وصوتك يگدر يغيّر مصير حد. منو تدافع عنه لو تهدد بالطرد؟",
        "⚖️ القانون بيدك مرة وحدة بس هاللعبة. اختار بحكمة منو تحميه.",
        "⚖️ لو صار تصويت ضد أحد، وياك الكلمة الفاصلة. منو تختار تدافع عنه؟",
        "⚖️ قضيتك جاهزة بس تحتاج متهم تدافع عنه. منو تختاره؟",
    ],
    "lawyer_defense_win": [
        "⚖️ بلحظة الحسم، المحامي طلع من بين الناس وگال كلمته - {name} ما راح يطلع اليوم!",
        "⚖️ الحبل كان لفّ برگبة {name}، بس المحامي فكّه بجملة وحدة وخلص القضية.",
        "⚖️ كل شي كان جاهز للطرد، لين المحامي رفع صوته ودافع عن {name} بآخر لحظة.",
        "⚖️ المحامي ما سكت هاي المرة - وقف وحمى {name} من حكم كان شبه مؤكد.",
    ],
}

# ============================================================
# طبقة الذكاء الاصطناعي الاختيارية - راوي القصص بالذكاء الاصطناعي
# ============================================================
# لو ANTHROPIC_API_KEY موجود بمتغيرات البيئة، كل مشهد موت يتولّد جديد
# ومختلف بالذكاء الاصطناعي (تنوع بلا حدود). لو ماكو مفتاح، أو صار أي
# خطأ (شبكة/رد غير متوقع)، يرجع تلقائيًا لبنك الجمل الثابت المختبر
# بالأعلى - اللعبة عمرها ما تتوقف بسبب مشكلة بالذكاء الاصطناعي.

ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY")
AI_NARRATION_ENABLED = bool(ANTHROPIC_API_KEY)

AI_SCENE_TOPIC = {
    "wolf_kill_scene": "مشهد قتل قصير ومرعب لضحية ذبحها ذيب بلعبة مافيا/ذئاب عراقية",
    "sk_kill_scene": "مشهد قتل هادئ وبارد الأعصاب لضحية سفاح بلعبة مافيا",
    "arsonist_kill_scene": "مشهد حريق قصير لضحية مضرم حرائق بلعبة مافيا",
}

def _call_anthropic_sync(prompt: str) -> str:
    """نداء HTTP متزامن لتوليد جملة سرد. يشتغل بخيط منفصل (asyncio.to_thread)
    حتى ما يوگف حلقة أحداث البوت. يرمي استثناء عند أي فشل، ويتم اصطياده بالمستدعي."""
    import urllib.request
    body = json.dumps({
        "model": "claude-haiku-4-5-20251001",
        "max_tokens": 150,
        "messages": [{"role": "user", "content": prompt}],
    }).encode("utf-8")
    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages",
        data=body,
        headers={
            "Content-Type": "application/json",
            "x-api-key": ANTHROPIC_API_KEY or "",
            "anthropic-version": "2023-06-01",
        },
    )
    with urllib.request.urlopen(req, timeout=8) as resp:
        data = json.loads(resp.read().decode("utf-8"))
    text = "".join(block.get("text", "") for block in data.get("content", []) if block.get("type") == "text")
    return text.strip()

async def ai_death_scene(name: str, category: str):
    """يولّد مشهد موت جديد بالذكاء الاصطناعي، أو يرجع None لو مو مفعّل أو صار خطأ
    (وبهاي الحالة المستدعي يرجع تلقائيًا لبنك الجمل الثابت)."""
    if not AI_NARRATION_ENABLED:
        return None
    topic = AI_SCENE_TOPIC.get(category)
    if not topic:
        return None
    prompt = (
        f"اكتب جملة أو جملتين بس، بلهجة عراقية عامية، تصف {topic}. "
        f"استخدم اسم الضحية '{name}' بالنص. خلي الأسلوب سينمائي ومثير بس بدون "
        f"تفاصيل جسدية فاحشة أو دموية زايدة عن اللزوم. جاوب بالنص بس، بلا مقدمة وبلا علامات اقتباس."
    )
    try:
        text = await asyncio.to_thread(_call_anthropic_sync, prompt)
        return text or None
    except Exception as exc:
        logger.warning("AI narration failed, falling back to static bank: %s", exc)
        return None


def narrator_pick(game: GameSession, category: str):
    options = NARRATION_BANK.get(category, [])
    unused = [x for x in options if x not in game.narration_used and x not in USED_NARRATION]
    if not unused:
        unused = [x for x in options if x not in game.narration_used] or options
    if not unused:
        return None
    line = random.choice(unused)
    game.narration_used.add(line)
    USED_NARRATION.add(line)
    save_used_narration(USED_NARRATION)
    return line

async def build_death_scene(game: GameSession, category: str, name: str, role_name: str) -> str:
    """يبني مشهد موت: يجرب الذكاء الاصطناعي أول (لو مفعّل)، وإلا يرجع لبنك
    الجمل الثابت المختبر (بلا تكرار)، وبعدين يكشف الدور تحت المشهد."""
    ai_scene = await ai_death_scene(name, category)
    if ai_scene:
        return f"💀 *{ai_scene}*\n\n_الدور: {role_name}_"

    scene = narrator_pick(game, category)
    if not scene:
        scene = "{name} انلگى ميت بالصبح، وماكو تفاصيل زيادة. 💀"
    scene = scene.format(name=f"*{name}*")
    return f"💀 {scene}\n\n_الدور: {role_name}_"

# ============================================================
# COMMAND HANDLERS
# ============================================================

async def announce_join(bot, game: GameSession, user):
    safe_name = html.escape(user.first_name or "لاعب")
    mention = f'<a href="tg://user?id={user.id}">{safe_name}</a>'
    await bot.send_message(
        chat_id=game.chat_id,
        text=f"🐺 أفلا انضم {mention} للعبة!",
        parse_mode="HTML"
    )


def add_player_to_game(game: GameSession, user):
    if user.id in game.players:
        return "already"
    if len(game.players) >= 20:
        return "full"
    game.players[user.id] = Player(user_id=user.id, name=user.first_name or "لاعب")
    user_games[user.id] = game.game_id
    return "joined"


async def join_from_deep_link(update: Update, context: ContextTypes.DEFAULT_TYPE, game_id: str):
    user = update.effective_user
    game = games.get(game_id)
    if not game or game.phase != GamePhase.WAITING:
        await update.message.reply_text("هاللعبة ما بقت مفتوحة يمعود.")
        return
    status = add_player_to_game(game, user)
    if status == "already":
        await update.message.reply_text("إنت داخل من قبل يمعود 😂")
        return
    if status == "full":
        await update.message.reply_text("اللعبة امتلت يمعود 😂")
        return
    chat_title = game.host_name
    try:
        chat = await context.bot.get_chat(game.chat_id)
        chat_title = chat.title or game.host_name
    except Exception:
        pass
    await update.message.reply_text(f"🐺 تم انضمامك بكروب «{chat_title}» بنجاح 😎")
    await announce_join(context.bot, game, user)


async def start_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle /start and private deep-link joining."""
    if context.args and context.args[0].startswith("join_"):
        game_id = context.args[0].split("_", 1)[1]
        await join_from_deep_link(update, context, game_id)
        return
    await update.message.reply_text(MSG["welcome"], parse_mode="Markdown")


async def newgame_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Create a new game session"""
    user = update.effective_user
    chat_id = update.effective_chat.id
    
    # Check if user already has an active game
    if user.id in user_games and user_games[user.id] in games:
        old_game = games[user_games[user.id]]
        if old_game.phase != GamePhase.ENDED:
            await update.message.reply_text(
                "يا {name}، عندك لعبة شغالة! إذا تريد تنهيها اكتب /endgame.".format(name=user.first_name)
            )
            return
    
    game_id = generate_game_id()
    game = GameSession(
        game_id=game_id,
        host_id=user.id,
        host_name=user.first_name,
        chat_id=chat_id
    )
    
    # Add host as first player
    game.players[user.id] = Player(
        user_id=user.id,
        name=user.first_name
    )
    
    games[game_id] = game
    user_games[user.id] = game_id

    for subscriber_id in list(nextgame_subscribers):
        try:
            await context.bot.send_message(chat_id=subscriber_id, text="🐺 يمعود، انفتحت لعبة جديدة! روح للكروب إذا تريد تلعب.")
        except Exception:
            pass
    nextgame_subscribers.clear()

    players_text = get_player_list_text(game.players)
    join_seconds = 60
    game.join_deadline = time.monotonic() + join_seconds
    bot_username = context.bot.username
    join_url = f"https://t.me/{bot_username}?start=join_{game_id}" if bot_username else None
    keyboard = InlineKeyboardMarkup([[InlineKeyboardButton("🚪 يلا دوس انضمام", url=join_url)]]) if join_url else None
    await update.message.reply_text(
        MSG["game_created"].format(
            host_name=user.first_name,
            game_id=game_id,
            count=len(game.players),
            max_players=20,
            players_list=players_text,
            seconds=join_seconds,
        ),
        parse_mode="Markdown",
        reply_markup=keyboard,
    )
    game.join_task = asyncio.create_task(join_timer(context.application, game_id))


async def join_timer(application: Application, game_id: str):
    while True:
        game = games.get(game_id)
        if not game or game.phase != GamePhase.WAITING or game.join_deadline is None:
            return
        remaining = game.join_deadline - time.monotonic()
        if remaining <= 0:
            await application.bot.send_message(
                chat_id=game.chat_id,
                text="⏰ خلص وقت الانضمام! صاحب اللعبة يگدر يبدي بـ /startgame إذا العدد صار 5 أو أكثر."
            )
            return
        await asyncio.sleep(min(remaining, 2))


async def extend_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user = update.effective_user
    game_id = user_games.get(user.id)
    game = games.get(game_id) if game_id else None
    if not game or game.phase != GamePhase.WAITING:
        await update.message.reply_text("ماكو جلسة مفتوحة هسة.")
        return
    if user.id != game.host_id:
        await update.message.reply_text("بس صاحب اللعبة يگدر يغيّر المهلة يمعود.")
        return
    if not context.args:
        await update.message.reply_text("اكتب مثل: /extend 30 حتى تزيد 30 ثانية، أو /extend -10 حتى تنقص 10 ثواني.")
        return
    try:
        delta = int(context.args[0])
    except ValueError:
        await update.message.reply_text("اكتب رقم صحيح يمعود، مثل /extend 30 أو /extend -10")
        return
    game.join_deadline = max(time.monotonic(), game.join_deadline + delta)
    remaining = max(0, int(game.join_deadline - time.monotonic()))
    if game.join_task is None or game.join_task.done():
        game.join_task = asyncio.create_task(join_timer(context.application, game.game_id))
    await update.message.reply_text(f"⏳ تم تعديل مهلة الانضمام. هسة باقي {remaining} ثانية.")


async def flee_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user = update.effective_user
    game_id = user_games.get(user.id)
    game = games.get(game_id) if game_id else None
    if not game or user.id not in game.players:
        await update.message.reply_text("إنت مو داخل بلعبة هسة يمعود.")
        return
    if game.phase != GamePhase.WAITING:
        await update.message.reply_text("ما تگدر تطلع بعد ما بدت اللعبة يمعود.")
        return
    if user.id == game.host_id:
        await update.message.reply_text("إنت صاحب اللعبة. إذا تريد توقفها استخدم /endgame.")
        return
    del game.players[user.id]
    user_games.pop(user.id, None)
    await update.message.reply_text("تمام، طلعت من اللعبة.")
    await context.bot.send_message(chat_id=game.chat_id, text=f"🚪 {user.first_name} طلع من الانتظار.")


async def nextgame_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    nextgame_subscribers.add(update.effective_user.id)
    await update.message.reply_text("تمام يمعود، من تنفتح لعبة جديدة أنبهك بالخاص إذا گدرت أوصلك.")


def get_player_title(games_played: int, wins: int) -> str:
    """لقب محسوب من عدد الألعاب والفوز - ماكو تخزين إضافي، يتحسب وقت العرض بس."""
    if games_played == 0:
        return "🆕 لاعب جديد"
    if wins >= 50:
        return "👑 أسطورة القرية"
    if wins >= 25:
        return "🐺 زعيم الذئاب"
    if wins >= 10:
        return "🔥 محترف"
    if wins >= 3:
        return "⭐ صاعد"
    if games_played >= 5:
        return "🎮 مخضرم"
    return "🌱 مبتدئ"


async def stats_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    st = await asyncio.to_thread(db_get_stats, update.effective_user.id)
    title = get_player_title(st.get('games', 0), st.get('wins', 0))
    text = (
        f"📊 إحصائياتك — {title}\n\n"
        f"🎮 لعبت: {st.get('games', 0)}\n"
        f"🏆 فوز: {st.get('wins', 0)}\n"
        f"💀 خسارة: {st.get('losses', 0)}\n"
        f"🗳️ أصوات: {st.get('votes', 0)}"
    )
    await update.message.reply_text(text)


async def leaderboard_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """يعرض أفضل 10 لاعبين حسب عدد مرات الفوز."""
    ranked = await asyncio.to_thread(db_get_leaderboard, 10)

    if not ranked:
        await update.message.reply_text("🏆 ماكو أحد لعب بعد! سووا /newgame وابدأوا 😎")
        return

    medals = ["🥇", "🥈", "🥉"]
    lines = ["🏆 *أفضل 10 لاعبين:*\n"]
    for i, s in enumerate(ranked):
        badge = medals[i] if i < 3 else f"{i + 1}."
        name = s.get("name") or f"لاعب {s.get('user_id')}"
        wins = s.get("wins", 0)
        games = s.get("games", 0)
        title = get_player_title(games, wins)
        lines.append(f"{badge} {name} — 🏆 {wins} فوز / 🎮 {games} لعبة\n   {title}")

    await update.message.reply_text("\n".join(lines), parse_mode="Markdown")


async def ping_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    started = time.perf_counter()
    msg = await update.message.reply_text("🏓 دا أفحص السرعة...")
    ms = int((time.perf_counter() - started) * 1000)
    await msg.edit_text(f"🏓 حاضر يمعود! سرعة الرد تقريباً {ms}ms")


async def chatid_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(f"🆔 آيدي هالمكان: `{update.effective_chat.id}`", parse_mode="Markdown")


async def version_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("🐺 نسخة بوت مافية الذئب العراقية: 1.0")


async def runinfo_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    active = sum(1 for g in games.values() if g.phase != GamePhase.ENDED)
    await update.message.reply_text(
        f"🧠 البوت شغال تمام.\n🎮 ألعاب شغالة: {active}\n🐺 الجلسات المحفوظة: {len(games)}"
    )


async def getstatus_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("🟢 البوت شغال زين يمعود.")


async def config_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "⚙️ الإعدادات الحالية:\n"
        "👥 أقل عدد: 5\n"
        "👥 أكثر عدد: 20\n"
        "⏳ مهلة الانضمام: تتغير بـ /extend\n"
        "🗳️ التصويت: بالخاص وينعلن بالمجموعة"
    )


async def donate_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("❤️ ما نطلب منك فلوس يمعود، دعمك للبوت إنك تلعب وتستانس بس 😂")


async def grouplist_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    waiting = [g for g in games.values() if g.phase == GamePhase.WAITING]
    if not waiting:
        await update.message.reply_text("ماكو جلسات مفتوحة هسة.")
        return
    lines = [f"• كود {g.game_id} - {len(g.players)}/20 لاعب" for g in waiting]
    await update.message.reply_text("🎮 الجلسات المفتوحة هسة:\n" + "\n".join(lines))


async def startchaos_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    game_id = user_games.get(update.effective_user.id)
    game = games.get(game_id) if game_id else None
    if not game or update.effective_user.id != game.host_id:
        await update.message.reply_text("بس صاحب اللعبة يگدر يبدي وضع الفوضى.")
        return
    game.chaos_mode = True
    await update.message.reply_text("🌪️ يلا، فعلنا وضع الفوضى! هسة أبدي اللعبة.")
    await startgame_command(update, context)


async def forcestart_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await startgame_command(update, context)


async def smite_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("⚡ هالأمر مخصص لإدارة البوت وما مفعل هسة حتى ما يصير ظلم باللعب.")


async def uploadlang_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("🌐 نظام ملفات اللغات مو محتاجينه هسة، لأن البوت عراقي من الأساس 😂🇮🇶")


async def validatelangs_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("🇮🇶 اللغة مضبوطة: عراقي بالكامل.")


async def join_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Join an existing game — scoped to the chat /join was sent in, so
    multiple groups running the bot at once never collide into one game."""
    user = update.effective_user
    chat_id = update.effective_chat.id
    
    if not games:
        await update.message.reply_text(MSG["no_game"])
        return
    
    # Only consider a waiting game that belongs to THIS chat
    available_game = None
    for gid, g in games.items():
        if g.phase == GamePhase.WAITING and g.chat_id == chat_id:
            available_game = g
            break
    
    if not available_game:
        await update.message.reply_text(MSG["no_game"])
        return
    
    # Check if already joined
    if user.id in available_game.players:
        await update.message.reply_text(
            MSG["already_joined"].format(name=user.first_name)
        )
        return
    
    # Check if game is full
    if len(available_game.players) >= 20:
        await update.message.reply_text(MSG["game_full"])
        return
    
    # Add player
    available_game.players[user.id] = Player(
        user_id=user.id,
        name=user.first_name
    )
    user_games[user.id] = available_game.game_id
    
    players_text = get_player_list_text(available_game.players)
    
    hint = ""
    if len(available_game.players) >= 5:
        hint = f"✅ العدد صار كافي! صاحب اللعبة يگدر يبدي بـ /startgame"
    else:
        remaining = 5 - len(available_game.players)
        hint = f"⏳ بعد ناقص {remaining} حتى نبدي"
    
    await update.message.reply_text(
        MSG["joined"].format(
            name=user.first_name,
            count=len(available_game.players),
            max=20,
            players_list=players_text,
            hint=hint
        ),
        parse_mode="Markdown"
    )


async def last_words_catcher(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """يلتقط رسالة اللاعب المطرود وقت نافذة 'آخر كلمة' ويعرضها بأسلوب درامي."""
    chat_id = update.effective_chat.id
    user = update.effective_user
    if chat_id not in LAST_WORDS_WINDOW or LAST_WORDS_WINDOW[chat_id] != user.id:
        return
    if not update.message or not update.message.text:
        return

    LAST_WORDS_WINDOW.pop(chat_id, None)
    await update.message.reply_text(
        f"🕯️ *آخر كلمات {user.first_name}:*\n\n_{update.message.text}_",
        parse_mode="Markdown"
    )


async def myrole_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """يرسل للاعب دوره وقدراته مرة ثانية بالخاص - مفيد لو نسى تفاصيل دوره وسط اللعبة."""
    user = update.effective_user

    if user.id not in user_games or user_games[user.id] not in games:
        await update.message.reply_text(MSG["no_game"])
        return

    game = games[user_games[user.id]]
    player = game.players.get(user.id)
    if not player or not player.role:
        await update.message.reply_text("دورك ما تحدد بعد - اللعبة لسة ما بدت.")
        return

    role_info = ROLES[player.role]
    status = "🟢 عايش" if player.alive else "💀 ميت"
    text = (
        f"{role_info['name']}\n\n"
        f"{role_info['description']}\n\n"
        f"{role_info['abilities']}\n\n"
        f"الحالة: {status}"
    )
    try:
        await context.bot.send_message(chat_id=user.id, text=text, parse_mode="Markdown")
        if update.effective_chat.id != user.id:
            await update.message.reply_text("✅ رسلتلك دورك بالخاص.")
    except Exception:
        await update.message.reply_text("⚠️ لازم تفتح خاص البوت (/start) حتى أگدر أرسلك دورك.")


async def kick_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """يخلي صاحب اللعبة يطرد لاعب انضم غلط، بس قبل ما تبدي اللعبة (WAITING بس)."""
    user = update.effective_user
    chat_id = update.effective_chat.id

    target_game = None
    for gid, g in games.items():
        if g.phase == GamePhase.WAITING and g.chat_id == chat_id:
            target_game = g
            break

    if not target_game:
        await update.message.reply_text(MSG["no_game"])
        return

    if target_game.host_id != user.id:
        await update.message.reply_text("بس صاحب اللعبة يگدر يطرد لاعب.")
        return

    target_id = None
    if update.message.reply_to_message:
        target_id = update.message.reply_to_message.from_user.id
    elif context.args:
        name_query = " ".join(context.args).strip().lower()
        for uid, p in target_game.players.items():
            if p.name.lower() == name_query:
                target_id = uid
                break

    if not target_id or target_id not in target_game.players:
        await update.message.reply_text("رد على رسالة اللاعب أو اكتب اسمه بالضبط: /kick اسم_اللاعب")
        return

    if target_id == target_game.host_id:
        await update.message.reply_text("ما تگدر تطرد نفسك، استخدم /endgame إذا تريد تلغي اللعبة.")
        return

    kicked_name = target_game.players[target_id].name
    del target_game.players[target_id]
    user_games.pop(target_id, None)
    await update.message.reply_text(f"🚫 طردنا {kicked_name} من اللعبة. العدد هسة: {len(target_game.players)}")


async def players_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Show current players"""
    user = update.effective_user
    
    if user.id not in user_games or user_games[user.id] not in games:
        await update.message.reply_text(MSG["no_game"])
        return
    
    game = games[user_games[user.id]]
    show_roles = game.phase == GamePhase.ENDED
    players_text = get_player_list_text(game.players, show_roles=show_roles)
    
    phase_text = {
        GamePhase.WAITING: "⏳ ننتظر",
        GamePhase.NIGHT: "🌙 ليل",
        GamePhase.MORNING: "☀️ صبح",
        GamePhase.DISCUSSION: "💬 حچي",
        GamePhase.VOTING: "🗳️ تصويت",
        GamePhase.ENDED: "🏁 خلصت",
    }.get(game.phase, "❓")
    
    await update.message.reply_text(
        f"🎮 *مافية الذئب - اللاعبين*\n\n"
        f"📊 هسة: {phase_text}\n"
        f"🔄 الجولة: {game.round_num}\n\n"
        f"{players_text}",
        parse_mode="Markdown"
    )


async def startgame_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Start the game (host only)"""
    user = update.effective_user
    
    if user.id not in user_games or user_games[user.id] not in games:
        await update.message.reply_text(MSG["no_game"])
        return
    
    game = games[user_games[user.id]]
    
    # Check if host
    if user.id != game.host_id:
        await update.message.reply_text(MSG["not_host"].format(name=user.first_name))
        return
    
    # Check minimum players
    if len(game.players) < 5:
        await update.message.reply_text(
            f"⛔ بعد ناقص لاعبين! نحتاج 5، وإنتو هسة {len(game.players)}"
        )
        return
    
    # سجّل بداية اللعبة بالإحصائيات
    for _uid, _p in game.players.items():
        await asyncio.to_thread(db_bump, _uid, _p.name, 1, 0, 0, 0)

    # Assign roles
    roles = assign_roles(len(game.players))
    if not roles:
        await update.message.reply_text("صار لخبطه بتوزيع الأدوار، جرّب مرة ثانية.")
        return
    
    for i, (uid, player) in enumerate(game.players.items()):
        player.role = roles[i]
        player.team = ROLES[roles[i]]["team"]
    
    # Start the game
    game.phase = GamePhase.NIGHT
    game.round_num = 1
    
    # ماكو أي فيديو يطلع ببداية اللعبة - رسالة نص بس.
    await update.message.reply_text(MSG["game_starting"], parse_mode="Markdown")
    
    # Send roles to each player via PM
    bot = context.bot
    for uid, player in game.players.items():
        role_info = ROLES[player.role]
        try:
            await bot.send_message(
                chat_id=uid,
                text=MSG["role_assigned"].format(
                    role_name=role_info["name"],
                    role_description=role_info["description"],
                    abilities=f"*قدراتك:*\n{role_info['abilities']}"
                ),
                parse_mode="Markdown"
            )
        except Exception as e:
            logger.warning(f"Could not PM role to {uid}: {e}")
            # If can't PM, announce in group (less ideal but works)
            pass
    
    # لا ننتظر مراحل اللعبة داخل الأمر، حتى تبقى الأوامر شغالة أثناء اللعب.
    async def _run_game_loop():
        try:
            await asyncio.sleep(3)
            await night_phase(update, context, game)
        except asyncio.CancelledError:
            raise
        except Exception:
            logger.exception("Game loop crashed for game %s", game.game_id)
            game.phase = GamePhase.ENDED
            try:
                await context.bot.send_message(update.effective_chat.id, "😵 صار لخبطه بالجولة، خلصناها حتى البوت ما يعلق. سوّوا لعبة جديدة.")
            except Exception:
                pass

    task = asyncio.create_task(_run_game_loop(), name=f"mafia-{game.game_id}")
    context.application.bot_data.setdefault("game_tasks", {})[game.game_id] = task


async def night_phase(update: Update, context: ContextTypes.DEFAULT_TYPE, game: GameSession):
    """Handle the night phase"""
    game.phase = GamePhase.HEALER
    game.night_kills = []
    chat_id = update.effective_chat.id
    for p in game.players.values():
        if hasattr(p, "_vote_target"):
            delattr(p, "_vote_target")
        if hasattr(p, "_sk_target"):
            delattr(p, "_sk_target")
        if hasattr(p, "_ignite_now"):
            delattr(p, "_ignite_now")
    
    # Reset protections
    for p in game.players.values():
        p.protected_by_healer = False
    
    bot = context.bot
    chat_id = update.effective_chat.id
    
    # Phase 1: Healer protects
    healers = [(uid, p) for uid, p in game.players.items() if p.role == "healer" and p.alive]
    if healers:
        for uid, healer in healers:
            targets = [(tid, t.name) for tid, t in game.players.items() if t.alive]
            keyboard = [[InlineKeyboardButton(t_name, callback_data=f"heal_{tid}")] for tid, t_name in targets]
            reply_markup = InlineKeyboardMarkup(keyboard)
            
            try:
                intro = narrator_pick(game, "healer_intro") or "⚕️ اختار واحد تريد تحميه هالليلة:"
                await bot.send_message(
                    chat_id=uid,
                    text=f"{intro}\n\n" + "\n".join([f"- {t_name}" for _, t_name in targets]),
                    reply_markup=reply_markup,
                    parse_mode="Markdown"
                )
            except:
                pass
    
    await asyncio.sleep(15)
    
    # Phase 2: Seer investigates
    game.phase = GamePhase.SEER
    seers = [(uid, p) for uid, p in game.players.items() if p.role == "seer" and p.alive]
    if seers:
        for uid, seer in seers:
            targets = [(tid, t.name) for tid, t in game.players.items() if t.alive and tid != uid]
            keyboard = [[InlineKeyboardButton(t_name, callback_data=f"seer_{tid}")] for tid, t_name in targets]
            reply_markup = InlineKeyboardMarkup(keyboard)
            
            try:
                intro = narrator_pick(game, "seer_intro") or "🔮 اختار واحد حتى تعرف شنو دوره:"
                await bot.send_message(
                    chat_id=uid,
                    text=f"{intro}\n\n" + "\n".join([f"- {t_name}" for _, t_name in targets]),
                    reply_markup=reply_markup,
                    parse_mode="Markdown"
                )
            except:
                pass
    
    await asyncio.sleep(15)
    
    # Phase 3: Wolves vote
    game.phase = GamePhase.WOLF
    wolves = [(uid, p) for uid, p in game.players.items() if p.role == "wolf" and p.alive]
    alive_civilians = [(uid, p) for uid, p in game.players.items() if p.alive and p.role != "wolf"]
    
    if wolves and alive_civilians:
        wolf_names = ", ".join([p.name for _, p in wolves])
        
        for uid, wolf in wolves:
            targets = [(tid, t.name) for tid, t in alive_civilians]
            keyboard = [[InlineKeyboardButton(t_name, callback_data=f"kill_{tid}")] for tid, t_name in targets]
            reply_markup = InlineKeyboardMarkup(keyboard)
            
            try:
                intro = narrator_pick(game, "wolf_intro") or "🐺 اختار منو تريدون تاكلون الليلة:"
                await bot.send_message(
                    chat_id=uid,
                    text=f"{intro}\n\n" + "\n".join([f"- {t_name}" for _, t_name in targets]) + "\n\n⏰ عندك 30 ثانية، لا تطوّل 😂",
                    reply_markup=reply_markup,
                    parse_mode="Markdown"
                )
            except:
                pass
    
    await asyncio.sleep(30)
    
    # Phase 4: Serial killer strikes (independent, ignores healer protection)
    game.phase = GamePhase.SERIAL_KILLER
    sks = [(uid, p) for uid, p in game.players.items() if p.role == "serial_killer" and p.alive]
    if sks:
        for uid, sk in sks:
            targets = [(tid, t.name) for tid, t in game.players.items() if t.alive and tid != uid]
            keyboard = [[InlineKeyboardButton(t_name, callback_data=f"sk_{tid}")] for tid, t_name in targets]
            reply_markup = InlineKeyboardMarkup(keyboard)
            try:
                intro = narrator_pick(game, "sk_intro") or "🔪 اختار ضحيتك الليلة (حمايه الحكيم ما تنفعهم منك):"
                await bot.send_message(
                    chat_id=uid,
                    text=f"{intro}\n\n" + "\n".join([f"- {t_name}" for _, t_name in targets]),
                    reply_markup=reply_markup,
                    parse_mode="Markdown"
                )
            except:
                pass
        await asyncio.sleep(20)
    
    # Phase 5: Arsonist douses or ignites
    game.phase = GamePhase.ARSONIST
    arsonists = [(uid, p) for uid, p in game.players.items() if p.role == "arsonist" and p.alive]
    if arsonists:
        for uid, ars in arsonists:
            targets = [(tid, t.name) for tid, t in game.players.items() if t.alive and tid != uid]
            keyboard = [[InlineKeyboardButton(f"⛽ {t_name}", callback_data=f"douse_{tid}")] for tid, t_name in targets]
            if game.arsonist_doused:
                keyboard.append([InlineKeyboardButton("🔥 ولّع الكل هسة!", callback_data="ignite_now")])
            reply_markup = InlineKeyboardMarkup(keyboard)
            ignite_note = "🔥 عندك خيار تولّع الكل هسة بدل الرش." if game.arsonist_doused else ""
            try:
                intro = narrator_pick(game, "arsonist_intro") or "🔥 ترش لاعب بالبنزين، أو تولّع كل اللي رشيتهم من قبل دفعة وحدة:"
                text = f"{intro}\n\n" + "\n".join([f"- {t_name}" for _, t_name in targets])
                if ignite_note:
                    text += f"\n\n{ignite_note}"
                await bot.send_message(
                    chat_id=uid,
                    text=text,
                    reply_markup=reply_markup,
                    parse_mode="Markdown"
                )
            except:
                pass
        await asyncio.sleep(20)
    
    # Process night results
    await process_night_results(update, context, game)


async def process_night_results(update: Update, context: ContextTypes.DEFAULT_TYPE, game: GameSession):
    """Process the results of the night phase"""
    bot = context.bot
    chat_id = update.effective_chat.id
    death_lines = []
    
    # Count wolf votes
    wolf_votes = {}
    for uid, player in game.players.items():
        if player.role == "wolf" and player.alive and hasattr(player, '_vote_target'):
            target = player._vote_target
            wolf_votes[target] = wolf_votes.get(target, 0) + 1
    
    # Pick the target with most votes
    if wolf_votes:
        max_votes = max(wolf_votes.values())
        top_targets = [t for t, v in wolf_votes.items() if v == max_votes]
        chosen_target = random.choice(top_targets)
        
        target_player = game.players.get(chosen_target)
        if target_player and target_player.alive:
            if not target_player.protected_by_healer:
                target_player.alive = False
                game.night_kills.append(chosen_target)
                
                death_lines.append(await build_death_scene(
                    game, "wolf_kill_scene", target_player.name, ROLES[target_player.role]["name"]
                ))
            else:
                death_lines.append(f"الحمدلله! {target_player.name} نجا بفضل الحكيم! 🛡️")
    else:
        # No votes, random target
        alive_non_wolves = [uid for uid, p in game.players.items() if p.alive and p.role != "wolf"]
        if alive_non_wolves:
            chosen = random.choice(alive_non_wolves)
            target_player = game.players[chosen]
            if not target_player.protected_by_healer:
                target_player.alive = False
                game.night_kills.append(chosen)
                death_lines.append(await build_death_scene(
                    game, "wolf_kill_scene", target_player.name, ROLES[target_player.role]["name"]
                ))
    
    # Serial killer strikes - bypasses healer protection entirely
    for uid, player in game.players.items():
        if player.role == "serial_killer" and player.alive and hasattr(player, "_sk_target"):
            target = game.players.get(player._sk_target)
            if target and target.alive:
                target.alive = False
                game.night_kills.append(target.user_id)
                death_lines.append(await build_death_scene(
                    game, "sk_kill_scene", target.name, ROLES[target.role]["name"]
                ))
                await send_serial_killer_effect(bot, chat_id)
    
    # Arsonist ignition - burns everyone doused so far, also bypasses protection
    for uid, player in game.players.items():
        if player.role == "arsonist" and player.alive and getattr(player, "_ignite_now", False):
            burned_any = False
            for tid in list(game.arsonist_doused):
                target = game.players.get(tid)
                if target and target.alive:
                    target.alive = False
                    game.night_kills.append(target.user_id)
                    death_lines.append(await build_death_scene(
                        game, "arsonist_kill_scene", target.name, ROLES[target.role]["name"]
                    ))
                    burned_any = True
            game.arsonist_doused.clear()
            if burned_any:
                await send_arsonist_burn_effect(bot, chat_id)
    
    death_msg = "\n\n".join(death_lines) if death_lines else None
    
    # Announce morning
    if death_msg:
        try:
            await bot.send_message(
                chat_id=chat_id,
                text=MSG["morning_arrives"].format(
                    death_message=death_msg,
                    alive_count=sum(1 for p in game.players.values() if p.alive),
                    alive_list=get_player_list_text({k: v for k, v in game.players.items() if v.alive}),
                    discussion_prompt="💬 *هسة وقت الحچي!* منو تشكون بيه؟"
                ),
                parse_mode="Markdown"
            )
        except:
            pass
    else:
        try:
            await bot.send_message(
                chat_id=chat_id,
                text=MSG["no_death"].format(
                    alive_count=sum(1 for p in game.players.values() if p.alive),
                    alive_list=get_player_list_text({k: v for k, v in game.players.items() if v.alive})
                ),
                parse_mode="Markdown"
            )
        except:
            pass
    
    # Check win condition
    if await check_win(update, context, game):
        return
    
    # Move to discussion
    await discussion_phase(update, context, game)


async def discussion_phase(update: Update, context: ContextTypes.DEFAULT_TYPE, game: GameSession):
    """مناقشة رواية تفاعلية: تنوع حسب وضع الجولة وما تعيد كلام سابق."""
    game.phase = GamePhase.DISCUSSION
    chat_id = game.chat_id or update.effective_chat.id
    opening = narrator_pick(game, "discussion_open")
    await context.bot.send_message(
        chat_id=chat_id,
        text=MSG["discussion_time"].format(seconds=60) + (f"\n\n{opening}" if opening else ""),
        parse_mode="Markdown"
    )

    # تدخلات متفرقة: بالبداية، حسب أحداث الجولة، وبنهاية الوقت.
    elapsed = 0
    checkpoints = [random.randint(8, 12), random.randint(10, 15), random.randint(10, 15), random.randint(8, 12)]
    for idx, delay in enumerate(checkpoints):
        if game.phase != GamePhase.DISCUSSION:
            return
        delay = min(delay, max(0, 55 - elapsed))
        if delay <= 0:
            break
        await asyncio.sleep(delay)
        elapsed += delay
        if game.phase != GamePhase.DISCUSSION:
            return
        if idx == 0 and game.night_kills:
            category = "after_death"
        elif idx == 0 and not game.night_kills:
            category = "after_save"
        elif elapsed >= 35:
            category = "late_discussion"
        else:
            category = "discussion_nudge"
        line = narrator_pick(game, category)
        if line:
            try:
                await context.bot.send_message(chat_id=chat_id, text=line)
            except Exception:
                logger.exception("Could not send discussion narration")

    remaining = max(0, 60 - elapsed)
    if remaining and game.phase == GamePhase.DISCUSSION:
        await asyncio.sleep(remaining)
    if game.phase == GamePhase.DISCUSSION:
        await voting_phase(update, context, game)


async def voting_phase(update: Update, context: ContextTypes.DEFAULT_TYPE, game: GameSession):
    """Handle the voting phase"""
    game.phase = GamePhase.VOTING
    game.votes = {}
    chat_id = update.effective_chat.id

    for p in game.players.values():
        if hasattr(p, "_protect_target"):
            delattr(p, "_protect_target")

    lawyers = [(uid, p) for uid, p in game.players.items() if p.role == "lawyer" and p.alive and not p.has_used_lawyer]
    alive_players_for_lawyer = [(uid, p.name) for uid, p in game.players.items() if p.alive]
    for uid, lawyer in lawyers:
        keyboard = [[InlineKeyboardButton(name, callback_data=f"lawyer_{tid}")] for tid, name in alive_players_for_lawyer if tid != uid]
        try:
            intro = narrator_pick(game, "lawyer_intro") or "⚖️ اختار واحد تدافع عنه إذا صار عليه أعلى أصوات (مرة وحدة بس):"
            await context.bot.send_message(chat_id=uid, text=intro, reply_markup=InlineKeyboardMarkup(keyboard))
        except Exception as e:
            logger.warning("Could not PM lawyer %s: %s", uid, e)
    
    alive_players = [(uid, p.name) for uid, p in game.players.items() if p.alive]
    
    keyboard = [[InlineKeyboardButton(name, callback_data=f"vote_{uid}")] for uid, name in alive_players]
    keyboard.append([InlineKeyboardButton("🚫 أسحب هالمرة", callback_data="vote_skip")])
    reply_markup = InlineKeyboardMarkup(keyboard)

    await context.bot.send_message(
        chat_id=chat_id,
        text=MSG["voting_time"],
        parse_mode="Markdown"
    )

    # التصويت ينعمل بالخاص، وكل صوت ينعلن فوراً بالمجموعة.
    for uid, name in alive_players:
        try:
            await context.bot.send_message(
                chat_id=uid,
                text=MSG["vote_private"],
                reply_markup=reply_markup
            )
        except Exception as e:
            logger.warning("Could not send private voting keyboard to %s: %s", uid, e)
            await context.bot.send_message(
                chat_id=chat_id,
                text=f"⚠️ ما گدرت أوصل التصويت بالخاص لـ {name}. لازم يفتح خاص البوت ويكتب /start."
            )

    await asyncio.sleep(60)
    
    # Process votes
    await process_votes(update, context, game)


async def process_votes(update: Update, context: ContextTypes.DEFAULT_TYPE, game: GameSession):
    """Process voting results"""
    chat_id = update.effective_chat.id
    
    if not game.votes:
        await context.bot.send_message(
            chat_id=chat_id,
            text="🤷 ماكو أصوات، نروح لليل الجاي...",
            parse_mode="Markdown"
        )
        # Next night
        await night_phase(update, context, game)
        return
    
    # Count votes
    vote_counts = {}
    for voter, target in game.votes.items():
        if target == "skip":
            continue
        vote_counts[target] = vote_counts.get(target, 0) + 1

    # كشف النتيجة الكاملة هسة بس - التصويت كان سري لين هالحظة.
    if vote_counts:
        reveal_lines = ["🗳️ *نتيجة التصويت السري:*\n"]
        for tid, count in sorted(vote_counts.items(), key=lambda kv: kv[1], reverse=True):
            tp = game.players.get(tid)
            name = tp.name if tp else "؟"
            reveal_lines.append(f"• {name}: {count} صوت")
        skip_count = sum(1 for t in game.votes.values() if t == "skip")
        if skip_count:
            reveal_lines.append(f"• 🚫 سحبوا: {skip_count}")
        await context.bot.send_message(
            chat_id=chat_id,
            text="\n".join(reveal_lines),
            parse_mode="Markdown"
        )
    
    if not vote_counts:
        await context.bot.send_message(
            chat_id=chat_id,
            text="🤷 الكل سحب، نروح لليل الجاي...",
            parse_mode="Markdown"
        )
        await night_phase(update, context, game)
        return
    
    max_votes = max(vote_counts.values())
    top_voted = [t for t, v in vote_counts.items() if v == max_votes]
    
    if len(top_voted) > 1:
        # Tie
        names = ", ".join([game.players.get(int(tid), Player(0, "Unknown")).name for tid in top_voted])
        await context.bot.send_message(
            chat_id=chat_id,
            text=MSG["tie_vote"].format(names=names),
            parse_mode="Markdown"
        )
        # Next night without elimination
        await night_phase(update, context, game)
        return
    
    # Eliminate the top voted
    eliminated_id = int(top_voted[0])
    eliminated = game.players.get(eliminated_id)
    
    if eliminated:
        lawyers = [p for p in game.players.values() if p.role == "lawyer" and p.alive and not p.has_used_lawyer]
        defender = next(
            (lawyer for lawyer in lawyers
             if hasattr(lawyer, "_protect_target") and lawyer._protect_target == eliminated_id),
            None
        )
        if defender:
            defender.has_used_lawyer = True
            defense_line = narrator_pick(game, "lawyer_defense_win") or f"⚖️ *المحامي دافع عن {eliminated.name}!*\n\nهالمرة ما راح يطلع 😎"
            defense_line = defense_line.format(name=eliminated.name) if "{name}" in defense_line else defense_line
            await context.bot.send_message(
                chat_id=chat_id,
                text=defense_line,
                parse_mode="Markdown"
            )
            await send_effect(context.bot, defender.user_id, "lawyer_defense.mp4", f"⚖️ دفاعك نجح وأنقذت {eliminated.name}!")
            await send_effect(context.bot, eliminated_id, "lawyer_defense.mp4", "🛡️ المحامي أنقذك من الطرد!")
            game.round_num += 1
            await night_phase(update, context, game)
            return

        eliminated.alive = False

        # 🕯️ آخر كلمة: نفتح نافذة 15 ثانية للمطرود يحچي قبل ما دوره ينكشف.
        LAST_WORDS_WINDOW[chat_id] = eliminated.user_id
        await context.bot.send_message(
            chat_id=chat_id,
            text=f"🤫 *سكتوا الكل...* {eliminated.name}، هذا وقتك الأخير تحچي (15 ثانية) 🕯️",
            parse_mode="Markdown"
        )
        await asyncio.sleep(15)
        LAST_WORDS_WINDOW.pop(chat_id, None)

        comments = [
            "خلصت سالفتك يمعود 😂",
            "يلا الله وياك 😂",
            "والله چنت شاك بيك 😂",
        ]
        
        # فيديو السكين مخصص للسفاح فقط، لذلك ما نستخدمه بالإقصاء العادي.
        await context.bot.send_message(
            chat_id=chat_id,
            text=MSG["elimination_result"].format(
                accused_name=eliminated.name,
                eliminated_message=MSG["player_eliminated"].format(
                    name=eliminated.name,
                    role=ROLES[eliminated.role]["name"],
                    comment=random.choice(comments)
                )
            ),
            parse_mode="Markdown"
        )

        # 🤡 الأخرق: لو انطرد بالتصويت (مو بالليل)، يفوز فورًا وتخلص اللعبة هنا.
        if eliminated.role == "fool":
            await context.bot.send_message(
                chat_id=chat_id,
                text=MSG["fool_win"].format(name=eliminated.name),
                parse_mode="Markdown"
            )
            await send_effect(context.bot, chat_id, "outcast_win.mp4", f"🤡 {eliminated.name} خدعكم كلكم!")
            for _uid, _p in game.players.items():
                if _uid == eliminated.user_id:
                    await asyncio.to_thread(db_bump, _uid, _p.name, 0, 1, 0, 0)
                else:
                    await asyncio.to_thread(db_bump, _uid, _p.name, 0, 0, 1, 0)
            game.phase = GamePhase.ENDED
            return

        # 💣 البداغ: لو انطرد بالتصويت، يفجّر لاعب عشوائي ثاني وياه.
        if eliminated.role == "bomber":
            other_alive = [p for p in game.players.values() if p.alive and p.user_id != eliminated.user_id]
            if other_alive:
                victim = random.choice(other_alive)
                victim.alive = False
                await context.bot.send_message(
                    chat_id=chat_id,
                    text=MSG["bomb_explosion"].format(bomber=eliminated.name, victim=victim.name),
                    parse_mode="Markdown"
                )
                await send_effect(context.bot, chat_id, "wolf_victory.mp4", f"💣 {victim.name} انفجر وياه!")
    
    # Check win condition
    if await check_win(update, context, game):
        return
    
    # Next round - night
    game.round_num += 1
    await night_phase(update, context, game)


async def check_win(update: Update, context: ContextTypes.DEFAULT_TYPE, game: GameSession) -> bool:
    """Check if any team has won"""
    chat_id = update.effective_chat.id
    
    alive_wolves = [p for p in game.players.values() if p.alive and p.team == "wolves"]
    alive_village = [p for p in game.players.values() if p.alive and p.team == "village"]
    total_alive = sum(1 for p in game.players.values() if p.alive)

    # Solo teams (outcast, serial killer, arsonist) each win if they're the
    # only team left standing - checked before wolves/village.
    solo_teams = {
        "outcast": ("outcast_win", "outcast_win.mp4", "🃏 {name} فاز وحده!"),
        "serial_killer": ("serial_killer_win", "serial_killer_attack.mp4", "🔪 {name} فاز وحده!"),
        "arsonist": ("arsonist_win", "arsonist_burn.mp4", "🔥 {name} فاز وحده!"),
    }
    for team_key, (msg_key, media_file, caption_tpl) in solo_teams.items():
        alive_solo = [p for p in game.players.values() if p.alive and p.team == team_key]
        if alive_solo and len(alive_solo) == total_alive:
            name = alive_solo[0].name
            await context.bot.send_message(
                chat_id=chat_id,
                text=MSG[msg_key].format(name=name),
                parse_mode="Markdown"
            )
            await send_effect(context.bot, chat_id, media_file, caption_tpl.format(name=name))
            await record_game_result(game, team_key)
            game.phase = GamePhase.ENDED
            return True

    solo_alive_any = any(
        p.alive and p.team in ("outcast", "serial_killer", "arsonist")
        for p in game.players.values()
    )
    wolves_win = (not solo_alive_any) and len(alive_wolves) >= len(alive_village) and len(alive_village) > 0
    village_win = (not solo_alive_any) and len(alive_wolves) == 0 and len(alive_village) > 0

    if wolves_win:
        wolves_list = "\n".join([f"🐺 {p.name}" for p in game.players.values() if p.role == "wolf"])
        await context.bot.send_message(
            chat_id=chat_id,
            text=MSG["wolves_win"].format(
                wolves_list=wolves_list,
                taunt=get_random_taunt(MSG["wolf_taunts"])
            ),
            parse_mode="Markdown"
        )
        await send_random_effect(context.bot, chat_id, ["wolf_victory.mp4", "wolf_victory_alt.mp4"], "🐺🩸 الذئاب فازوا!")
        await record_game_result(game, "wolves")
        game.phase = GamePhase.ENDED
        return True
    
    if village_win:
        survivors = [p for p in game.players.values() if p.alive]
        survivors_list = "\n".join([f"🛡️ {p.name}" for p in survivors])
        await context.bot.send_message(
            chat_id=chat_id,
            text=MSG["village_win"].format(
                survivors_list=survivors_list,
                celebration=get_random_taunt(MSG["village_celebrations"])
            ),
            parse_mode="Markdown"
        )
        await send_effect(context.bot, chat_id, "village_win.mp4", "🏆🎉 أهل القرية فازوا!")
        await record_game_result(game, "village")
        game.phase = GamePhase.ENDED
        return True
    
    return False


async def endgame_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """End the current game"""
    user = update.effective_user
    
    if user.id not in user_games or user_games[user.id] not in games:
        await update.message.reply_text(MSG["no_game"])
        return
    
    game = games[user_games[user.id]]
    
    if user.id != game.host_id:
        await update.message.reply_text(MSG["not_host"].format(name=user.first_name))
        return
    
    game.phase = GamePhase.ENDED
    await update.message.reply_text(MSG["game_ended"])


async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Show help message"""
    await update.message.reply_text(MSG["help"], parse_mode="Markdown")


async def rules_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Show game rules"""
    await update.message.reply_text(MSG["rules"], parse_mode="Markdown")


# ============================================================
# CALLBACK HANDLERS
# ============================================================

async def button_callback(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle inline buttons with strict phase/role validation."""
    query = update.callback_query
    await query.answer()
    user = update.effective_user
    data = query.data or ""

    if user.id not in user_games or user_games[user.id] not in games:
        await query.edit_message_text("ماكو لعبة شغالة!")
        return

    game = games[user_games[user.id]]
    player = game.players.get(user.id)
    if not player:
        await query.edit_message_text("إنت مو داخل بهاللعبة!")
        return
    if not player.alive:
        await query.answer("إنت ميت يمعود، ما تگدر تسوي شي هسة 😂", show_alert=True)
        return

    async with game.lock:
        if data.startswith("heal_"):
            if player.role != "healer" or game.phase != GamePhase.HEALER:
                await query.answer("هسة مو دور الحكيم.", show_alert=True)
                return
            target_id = int(data.split("_", 1)[1])
            target = game.players.get(target_id)
            if not target or not target.alive:
                await query.answer("هذا اللاعب ما تگدر تختاره هسة.", show_alert=True)
                return
            if target_id == user.id and game.last_protected == user.id:
                await query.answer("ما تگدر تحمي نفسك ليلتين ورا بعض يمعود.", show_alert=True)
                return
            for p in game.players.values():
                p.protected_by_healer = False
            target.protected_by_healer = True
            game.last_protected = target_id
            await query.edit_message_text(f"✅ حميت {target.name} هالليلة!\n{narrator_pick(game, 'healer_confirm')}")
            await send_effect(context.bot, user.id, "healer_save.mp4", f"🛡️ حميت {target.name} بنجاح!")

        elif data.startswith("seer_"):
            if player.role != "seer" or game.phase != GamePhase.SEER:
                await query.answer("هسة مو دور العرّاف.", show_alert=True)
                return
            target_id = int(data.split("_", 1)[1])
            target = game.players.get(target_id)
            if not target or not target.alive or target_id == user.id:
                await query.answer("هذا اللاعب ما تگدر تختاره هسة.", show_alert=True)
                return
            result = "🐺 *ذيب!*" if target.role == "wolf" else "🛡️ *مو ذيب*"
            comments = [
                "صح عليك! كشفته 😂👁️",
                "هاي النتيجة، لا تفضح روحك 😂🤫",
                "خوش كشف يمعود 😂",
            ]
            await query.edit_message_text(
                MSG["seer_result"].format(name=target.name, result=result, comment=random.choice(comments)),
                parse_mode="Markdown"
            )
            await send_effect(context.bot, user.id, "seer_check.mp4", f"🔮 نتيجة الكشف: {target.name}")

        elif data.startswith("kill_"):
            if player.role != "wolf" or game.phase != GamePhase.WOLF:
                await query.answer("هسة مو دور الذيب.", show_alert=True)
                return
            target_id = int(data.split("_", 1)[1])
            target = game.players.get(target_id)
            if not target or not target.alive or target.role == "wolf":
                await query.answer("ما تگدر تختار هذا يمعود.", show_alert=True)
                return
            player._vote_target = target_id
            await query.edit_message_text(f"✅ اخترت {target.name}\n{narrator_pick(game, 'wolf_confirm')}")

        elif data.startswith("sk_"):
            if player.role != "serial_killer" or game.phase != GamePhase.SERIAL_KILLER:
                await query.answer("هسة مو دورك.", show_alert=True)
                return
            target_id = int(data.split("_", 1)[1])
            target = game.players.get(target_id)
            if not target or not target.alive or target_id == user.id:
                await query.answer("ما تگدر تختار هذا يمعود.", show_alert=True)
                return
            player._sk_target = target_id
            await query.edit_message_text(f"🔪 اخترت ضحيتك: {target.name}\n{narrator_pick(game, 'sk_confirm')}")

        elif data.startswith("douse_"):
            if player.role != "arsonist" or game.phase != GamePhase.ARSONIST:
                await query.answer("هسة مو دورك.", show_alert=True)
                return
            target_id = int(data.split("_", 1)[1])
            target = game.players.get(target_id)
            if not target or not target.alive or target_id == user.id:
                await query.answer("ما تگدر تختار هذا يمعود.", show_alert=True)
                return
            game.arsonist_doused.add(target_id)
            await query.edit_message_text(f"⛽ رشيت {target.name} بالبنزين\n{narrator_pick(game, 'arsonist_confirm_douse')}")

        elif data == "ignite_now":
            if player.role != "arsonist" or game.phase != GamePhase.ARSONIST:
                await query.answer("هسة مو دورك.", show_alert=True)
                return
            if not game.arsonist_doused:
                await query.answer("ماكو أحد مرشوش بعد يمعود.", show_alert=True)
                return
            player._ignite_now = True
            await query.edit_message_text("🔥 ولّعتها! راح تشوف النتيجة الصبح.")

        elif data.startswith("lawyer_"):
            if player.role != "lawyer" or game.phase != GamePhase.VOTING:
                await query.answer("هسة مو دور المحامي.", show_alert=True)
                return
            if player.has_used_lawyer:
                await query.answer("دفاعك مستعمله من قبل يمعود.", show_alert=True)
                return
            target_id = int(data.split("_", 1)[1])
            target = game.players.get(target_id)
            if not target or not target.alive:
                await query.answer("هذا اللاعب ما تگدر تختاره هسة.", show_alert=True)
                return
            player._protect_target = target_id
            await query.edit_message_text(f"⚖️ اخترت تدافع عن {target.name} إذا طلع بالتصويت.")
            await send_effect(context.bot, user.id, "lawyer_defense.mp4", f"⚖️ جهزت دفاعك عن {target.name}!")

        elif data.startswith("vote_"):
            if game.phase != GamePhase.VOTING:
                await query.answer("هسة مو وقت التصويت يمعود.", show_alert=True)
                return
            if data == "vote_skip":
                if user.id in game.votes:
                    await query.answer("إنت مصوّت من قبل.", show_alert=True)
                    return
                game.votes[user.id] = "skip"
                await query.edit_message_text("🚫 قررت تسحب هالمرة.")
                await context.bot.send_message(
                    chat_id=game.chat_id,
                    text=f"🗳️ صوّت {len(game.votes)}/{sum(1 for p in game.players.values() if p.alive)} لحد هسة (التصويت سري لين النهاية 🤫)"
                )
                return
            target_id = int(data.split("_", 1)[1])
            target = game.players.get(target_id)
            if not target or not target.alive:
                await query.answer("هذا اللاعب ما تگدر تختاره هسة.", show_alert=True)
                return
            if user.id in game.votes:
                await query.answer("إنت مصوّت من قبل يمعود 😂", show_alert=True)
                return
            game.votes[user.id] = target_id
            await asyncio.to_thread(db_bump, user.id, player.name, 0, 0, 0, 1)
            await query.edit_message_text(MSG["vote_cast"])

            # التصويت سري: نعلن بس العداد بالمجموعة، وما نكشف منو صوّت على منو
            # إلا لما تخلص فترة التصويت كلها (بدالة process_votes).
            alive_count = sum(1 for p in game.players.values() if p.alive)
            await context.bot.send_message(
                chat_id=game.chat_id,
                text=f"🗳️ صوّت {len(game.votes)}/{alive_count} لحد هسة (التصويت سري لين النهاية 🤫)"
            )


# ============================================================
# MAIN
# ============================================================

async def setup_commands(application: Application):
    """Set up bot commands menu"""
    commands = [
        BotCommand("start", "شغّل البوت"),
        BotCommand("newgame", "سوّي جلسة جديدة"),
        BotCommand("startgame", "ابدأ اللعب"),
        BotCommand("startchaos", "ابدأ الفوضى"),
        BotCommand("extend", "غيّر مهلة الانضمام"),
        BotCommand("players", "شوف اللاعبين"),
        BotCommand("myrole", "شوف دورك مرة ثانية"),
        BotCommand("kick", "اطرد لاعب (صاحب اللعبة بس)"),
        BotCommand("flee", "اطلع من اللعبة"),
        BotCommand("nextgame", "نبهني للجولة الجاية"),
        BotCommand("stats", "إحصائياتك"),
        BotCommand("leaderboard", "أفضل اللاعبين"),
        BotCommand("ping", "افحص سرعة البوت"),
        BotCommand("chatid", "طلع آيدي المكان"),
        BotCommand("version", "نسخة البوت"),
        BotCommand("runinfo", "معلومات التشغيل"),
        BotCommand("getstatus", "حالة البوت"),
        BotCommand("config", "إعدادات الجلسة"),
        BotCommand("forcestart", "ابدأ بالقوة"),
        BotCommand("donate", "دعم البوت بدون فلوس 😂"),
        BotCommand("grouplist", "الجلسات المفتوحة"),
        BotCommand("smite", "أمر إدارة"),
        BotCommand("uploadlang", "أمر إدارة اللغة"),
        BotCommand("validatelangs", "تدقيق اللغة"),
        BotCommand("endgame", "خلص اللعبة"),
        BotCommand("rules", "قوانين اللعب"),
        BotCommand("help", "شنو تسوي؟"),
    ]
    await application.bot.set_my_commands(commands)

def main():
    """Run the bot"""
    token = TOKEN
    if not token:
        raise RuntimeError("BOT_TOKEN is not set. Put it in the server environment; do not hard-code it in source code.")
    
    application = Application.builder().token(token).build()
    
    # Command handlers
    application.add_handler(CommandHandler("start", start_command))
    application.add_handler(CommandHandler("newgame", newgame_command))
    application.add_handler(CommandHandler("players", players_command))
    application.add_handler(CommandHandler("myrole", myrole_command))
    application.add_handler(CommandHandler("kick", kick_command))
    application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, last_words_catcher))
    application.add_handler(CommandHandler("startgame", startgame_command))
    application.add_handler(CommandHandler("startchaos", startchaos_command))
    application.add_handler(CommandHandler("extend", extend_command))
    application.add_handler(CommandHandler("flee", flee_command))
    application.add_handler(CommandHandler("nextgame", nextgame_command))
    application.add_handler(CommandHandler("stats", stats_command))
    application.add_handler(CommandHandler("leaderboard", leaderboard_command))
    application.add_handler(CommandHandler("ping", ping_command))
    application.add_handler(CommandHandler("chatid", chatid_command))
    application.add_handler(CommandHandler("version", version_command))
    application.add_handler(CommandHandler("runinfo", runinfo_command))
    application.add_handler(CommandHandler("getstatus", getstatus_command))
    application.add_handler(CommandHandler("config", config_command))
    application.add_handler(CommandHandler("forcestart", forcestart_command))
    application.add_handler(CommandHandler("donate", donate_command))
    application.add_handler(CommandHandler("grouplist", grouplist_command))
    application.add_handler(CommandHandler("smite", smite_command))
    application.add_handler(CommandHandler("uploadlang", uploadlang_command))
    application.add_handler(CommandHandler("validatelangs", validatelangs_command))
    application.add_handler(CommandHandler("endgame", endgame_command))
    application.add_handler(CommandHandler("help", help_command))
    application.add_handler(CommandHandler("rules", rules_command))
    
    # Callback handler
    application.add_handler(CallbackQueryHandler(button_callback))
    
    # Post-init
    application.post_init = setup_commands
    
    print("🐺 بوت مافية الذئب شغال! يلا العبوا!")
    application.run_polling(allowed_updates=Update.ALL_TYPES)


if __name__ == "__main__":
    main()
