#!/usr/bin/env python3
"""
مافية عصام - بوت تليجرام للعبة مافيا بلهجة عراقية
Mafia Essam - Telegram Bot for Werewolf/Mafia Game in Iraqi Dialect

Author: Generated by AI
Requirements: python-telegram-bot>=20.0
"""

import os
import random
import logging
import asyncio
import time
import html
from typing import Dict, List, Optional
from dataclasses import dataclass, field
from enum import Enum

from telegram import (
    Update, InlineKeyboardButton, InlineKeyboardMarkup,
    BotCommand, CallbackQuery
)
from telegram.ext import (
    Application, CommandHandler, CallbackQueryHandler,
    ContextTypes, ConversationHandler, MessageHandler, filters
)

# ============================================================
# CONFIGURATION
# ============================================================

logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    level=logging.INFO
)
logger = logging.getLogger(__name__)

# Get token from environment variable
TOKEN = os.environ.get("BOT_TOKEN")
MEDIA_DIR = os.path.join(os.path.dirname(__file__), "media")

# الفيديوهات موزعة حسب الحالة فقط:
# بداية اللعبة = القمر، الحريق = مضرم الحرائق، السكين = السفاح.
EVENT_EFFECTS = {
    "game_start": "game_start_moon.mp4",
    "arsonist_burn": "arsonist_burn.mp4",
    "serial_killer_attack": "serial_killer_attack.mp4",
}


async def send_arsonist_burn_effect(bot, chat_id: int):
    """تأثير الحريق، مخصص حصراً لمضرم الحرائق لما يحرق البيت."""
    return await send_effect(bot, chat_id, EVENT_EFFECTS["arsonist_burn"], "🔥🏠 مضرم الحرائق ولّع البيت!")


async def send_serial_killer_effect(bot, chat_id: int):
    """تأثير السكين، مخصص حصراً لهجوم السفاح."""
    return await send_effect(bot, chat_id, EVENT_EFFECTS["serial_killer_attack"], "🔪 السفاح ضرب ضربته!")


async def send_effect(bot, chat_id: int, filename: str, caption: str = None):
    """Send a short local MP4 effect; silently fall back if the media is unavailable."""
    path = os.path.join(MEDIA_DIR, filename)
    if not os.path.isfile(path):
        return False
    try:
        with open(path, "rb") as video:
            await bot.send_video(
                chat_id=chat_id,
                video=video,
                caption=caption,
                supports_streaming=True,
                width=480,
                height=640,
            )
        return True
    except Exception as exc:
        logger.warning("Could not send effect %s to %s: %s", filename, chat_id, exc)
        return False

async def send_random_effect(bot, chat_id: int, filenames, caption: str = None):
    """Pick one local effect at random from the supplied event-specific files."""
    available = [name for name in filenames if os.path.isfile(os.path.join(MEDIA_DIR, name))]
    if not available:
        return False
    return await send_effect(bot, chat_id, random.choice(available), caption)


# ============================================================
# IRAQI MESSAGES - بهجة عراقية خالصة
# ============================================================

MSG = {
    "welcome": """
🐺 *هلا فيك في بوت مافية الذئب*
*عصام @eia_qw* 🇮🇶

*شلون تلعب؟*
1️⃣ تريد تسوي لعبة جديدة؟ اكتب /newgame
2️⃣ من تنفتح اللعبة دوس زر *يلا دوس انضمام*
3️⃣ من يكتمل العدد، صاحب اللعبة يكتب /startgame

*أقل شي:* 5 لاعبين | *أكثر شي:* 20 لاعب

_يلا شبيك؟ ادخل ويانه وخلي نشوف منو يطلع ذيب 😂🐺_
""",
    "game_created": """
🎮 *يلااا انفتحت لعبة جديدة!*

صاحب اللعبة: {host_name}
كود اللعبة: `{game_id}`

اللاعبين ({count}/{max_players}):
{players_list}

👇 اللي يريد يدخل، بس دوس الزر جوه
⏳ *باقي على الانضمام: {seconds} ثانية*
""",
    "joined": """
✅ *هلا {name}، دخلت ويانه!*

عدد اللاعبين هسة: {count}/{max}
{players_list}

{hint}
""",
    "already_joined": "يا {name}، إنت داخل من قبل يمعود 😂",
    "game_full": "اللعبة امتلت يمعود 😂 انتظر الجولة الجاية.",
    "no_game": "ماكو لعبة شغالة هسة! سوّوا وحدة بـ /newgame",
    "not_host": "يا {name}، بس صاحب اللعبة يگدر يبديها 😅",
    "game_starting": """
🌙 *يلااا بدت اللعبة!* 🐺

هسة راح نوزع الأدوار... انتظروا شوي 🤫
""",
    "role_assigned": """
🎭 *دورك: {role_name}*

{role_description}

{abilities}

*لا تفضح دورك يمعود!* خليها سر بيناتنا 🤫
""",
    "night_falls": """
🌙 *حل الليل...*

الكل نام، بس أكو ناس هسة راح تشتغل 😈

{actions}
""",
    "wolf_prompt": """
🐺 *إنت ذيب!*

اختار منو تريدون تاكلون الليلة:
{targets}

{timer_warning}
""",
    "seer_prompt": """
🔮 *إنت العرّاف!*

اختار واحد حتى تعرف شنو دوره:
{targets}
""",
    "healer_prompt": """
⚕️ *إنت الحكيم!*

اختار واحد تريد تحميه هالليلة:
{targets}
""",
    "seer_result": """
🔮 *طلعت النتيجة:*

{name} → {result}

{comment}
""",
    "morning_arrives": """
☀️ *طلع الصبح!*

{death_message}

*اللي بعدهم عايشين ({alive_count}):*
{alive_list}

{discussion_prompt}
""",
    "no_death": """
☀️ *طلع الصبح!*

الحمدلله، هالليلة ما مات أحد! 🙏
شكله الحكيم لحق وأنقذ واحد 😎

*اللي بعدهم عايشين ({alive_count}):*
{alive_list}
""",
    "death_announcement": """
💀 *يا ساتر!* 💀

هالليلة {name} ({role}) {cause}

_الله يرحمه... الذئاب ما تعرف الرحمة 😂🐺_
""",
    "discussion_time": """
💬 *هسة وقت الحچي!* 💬

يلا منو تشكون بيه؟ كل واحد يحچي ويدافع عن روحه 😂

⏰ *عندكم {seconds} ثانية*

وبعدين نروح للتصويت! 🗳️
""",
    "voting_time": """
🗳️ *هسة وقت التصويت!*

كل واحد يروح لخاص البوت ويختار منو يصوّت عليه.
من يصوّت، صوته يطلع فوراً هنا بالمجموعة.

⏰ *عندكم 60 ثانية*
""",
    "vote_private": "🗳️ اختار منو تريد تصوّت عليه:",
    "vote_cast": "✅ تم، صوتك انحسب!",
    "already_voted": "يا {name}، إنت مصوّت من قبل 😂 ما يصير مرتين!",
    "elimination_result": """
⚔️ *خلص التصويت!*

👤 *المتهم: {accused_name}*

{eliminated_message}
""",
    "player_eliminated": """
💀 *{name} طلع من اللعبة!* 💀

دوره الحقيقي: *{role}*

{name} {comment}
""",
    "tie_vote": """
🤝 *صار تعادل!*

{names} طلع عدهم نفس عدد الأصوات!

هالمرة محد ينطرد... بس انتبهوا للجولة الجاية 😂
""",
    "wolves_win": """
🐺 *الذيب فاز باللعبة!* 🔥

🏆 *الذئاب الفايزين:*
{wolves_list}

{taunt}
""",
    "village_win": """
🏆 *أهل القرية فازوا!* 🎉

🛡️ *اللي ظلوا عايشين:*
{survivors_list}

{celebration}
""",
    "outcast_win": """
🃏 *المنبوذ فاز وحده!* 😂

{name} ظل للنهاية وسواها!

خوش لعب يمعود 😎🔥
""",
    "wolf_taunts": [
        "😂 الذئاب سووها وبلعوا القرية كلها!",
        "😈 أهل القرية شكد حاولوا... بس الذيب لعبها صح!",
        "🐺 عصام عمكم بس 😎🔥",
    ],
    "village_celebrations": [
        "😂 خوش لعب! كشفوهم قبل لا يبلعونكم.",
        "🧠 لعبتوها صح، الذئاب ما لگوا مخرج.",
        "🇮🇶 خوش شغل يا أهل القرية!",
    ],
    "game_ended": "🛑 خلصت اللعبة! إذا تريدون لعبة جديدة اكتبوا /newgame",
    "game_reset": "✅ رجعناها من جديد! هسة اكتبوا /newgame",
    "not_in_game": "يا {name}، إنت مو داخل بهاللعبة يمعود.",
    "help": """
📜 *أوامر بوت مافية الذئب:*

/newgame - تسوي لعبة جديدة
/startgame - تبدي اللعبة
/startchaos - تبدي وضع الفوضى
/extend - تزيد أو تقلل مهلة الانضمام
/players - تشوف منو داخل
/flee - تطلع من اللعبة
/nextgame - ينبهك بالخاص للجولة الجاية
/stats - إحصائياتك
/ping - يفحص سرعة البوت
/chatid - يطلع آيدي الكروب
/version - نسخة البوت
/runinfo - معلومات التشغيل
/config - إعدادات الجلسة
/forcestart - يبدي اللعبة بالقوة
/endgame - يخلص اللعبة
/rules - القوانين
/help - هاي القائمة

*ملاحظة:* الدخول يصير من زر *يلا دوس انضمام*، مو بأمر كتابة.
""",
    "rules": """
📋 *قوانين اللعبة:*

*شلون يفوزون؟*
🐺 الذئاب: ياكلون الباقين لحد ما يصير عددهم مثلهم أو أكثر.
🛡️ أهل القرية: يكشفون الذئاب ويطلعوهم من اللعبة.

*الأدوار:*
🐺 *الذيب* - بالليل يختار ضحية
🔮 *العرّاف* - يعرف دور لاعب
⚕️ *الحكيم* - يحمي لاعب من الهجوم
⚖️ *المحامي* - ينقذ لاعب من الطرد مرة وحدة
🃏 *المنبوذ* - يريد يبقى وحده بالنهاية

*مراحل اللعبة:*
1️⃣ بالليل: كل صاحب دور يسوي شغلته
2️⃣ بالصبح: نعرف شصار
3️⃣ الحچي: الكل يتهم ويدافع عن روحه
4️⃣ التصويت: تختارون منو يطلع
5️⃣ ونبقى نعيد لحد ما يفوز فريق

*لا تفضح دورك بالخاص، خلي اللعب حماس 😂*
""",
}

# ============================================================
# ROLES DATA
# ============================================================

ROLES = {
    "wolf": {
        "name": "🐺 الذيب",
        "team": "wolves",
        "description": "إنت ويا فريق الذئاب! 🐺\n"
                      "كل ليلة تگعدون وتختارون واحد.\n"
                      "هدفكم تاكلون الباقين لحد ما يصير عددكم كدهم أو أكثر!",
        "abilities": "🗡️ تختارون ضحية كل ليلة\n"
                    "👁️ تعرف باقي الذئاب من البداية\n"
                    "🎭 تگدر تخدع الباقين بالحچي",
    },
    "civilian": {
        "name": "🛡️ المدني",
        "team": "village",
        "description": "إنت مدني بريء! 🛡️\n"
                      "ما عندك قدرة خاصة، بس مخك وحسك يكفون.\n"
                      "دور على الذئاب وصوّت عليهم!",
        "abilities": "🧠 استخدم مخك حتى تكشف الذئاب\n"
                    "💬 احچي وناقش وصوّت\n"
                    "🗳️ صوتك يفرق مثل الباقين!",
    },
    "seer": {
        "name": "🔮 العرّاف",
        "team": "village",
        "description": "إنت العرّاف! 🔮\n"
                      "كل ليلة تگدر تعرف دور واحد.\n"
                      "بس لا تفضح نفسك للذئاب!",
        "abilities": "🔍 تعرف دور لاعب واحد كل ليلة\n"
                    "👁️ تعرف إذا اللاعب ذيب لو لا\n"
                    "⚠️ الذئاب يحبون يخلصون منك بسرعة!",
    },
    "healer": {
        "name": "⚕️ الحكيم",
        "team": "village",
        "description": "إنت الحكيم! ⚕️\n"
                      "كل ليلة تگدر تحمي واحد من الذئاب.\n"
                      "بس ما تگدر تحمي نفسك ليلتين ورا بعض!",
        "abilities": "🛡️ تحمي لاعب من هجوم الذئاب كل ليلة\n"
                    "🚫 ما تگدر تحمي نفسك مرتين ورا بعض\n"
                    "💪 حمايتك ممكن تنقذ واحد!",
    },
    "lawyer": {
        "name": "⚖️ المحامي",
        "team": "village",
        "description": "إنت المحامي! ⚖️\n"
                      "تگدر تنقذ لاعب من الطرد مرة وحدة بس باللعبة!",
        "abilities": "🛡️ تدافع عن لاعب من الطرد (مرة وحدة)\n"
                    "💼 دفاعك ينقذه حتى لو الأصوات عليه أكثر",
    },
    "outcast": {
        "name": "🃏 المنبوذ",
        "team": "outcast",
        "description": "إنت المنبوذ! 🃏\n"
                      "مو ويا الذئاب ولا ويا القرية.\n"
                      "كل همك تبقى وحدك بالنهاية!",
        "abilities": "🎯 تفوز إذا بقيت للنهاية وحدك\n"
                    "🤫 مو مهم منو يفوز، المهم تبقى عايش!\n"
                    "🎭 لخبطهم كلهم وخليك متخفي!",
    },
}

# ============================================================
# GAME STATE
# ============================================================

class GamePhase(Enum):
    WAITING = "waiting"
    NIGHT = "night"
    SEER = "seer"
    HEALER = "healer"
    WOLF = "wolf"
    MORNING = "morning"
    DISCUSSION = "discussion"
    VOTING = "voting"
    ELIMINATION = "elimination"
    ENDED = "ended"


@dataclass
class Player:
    user_id: int
    name: str
    role: str = ""
    team: str = ""
    alive: bool = True
    protected_by_healer: bool = False
    protected_by_lawyer: bool = False
    has_used_lawyer: bool = False


@dataclass
class GameSession:
    game_id: str
    host_id: int
    host_name: str
    players: Dict[int, Player] = field(default_factory=dict)
    phase: GamePhase = GamePhase.WAITING
    round_num: int = 0
    last_protected: int = None
    night_kills: List[int] = field(default_factory=list)
    votes: Dict[int, int] = field(default_factory=dict)
    wolf_chat_id: int = None
    chat_id: int = None
    chaos_mode: bool = False
    join_deadline: float = None
    join_task: object = None


# ============================================================
# GLOBAL GAMES STORE
# ============================================================

games: Dict[str, GameSession] = {}
user_games: Dict[int, str] = {}  # user_id -> game_id
nextgame_subscribers: set[int] = set()
player_stats: Dict[int, Dict[str, int]] = {}


# ============================================================
# UTILITY FUNCTIONS
# ============================================================

def get_random_taunt(taunts_list):
    return random.choice(taunts_list)


def generate_game_id():
    return str(random.randint(10000, 99999))


def get_role_emoji(role):
    emojis = {
        "wolf": "🐺",
        "civilian": "🛡️",
        "seer": "🔮",
        "healer": "⚕️",
        "lawyer": "⚖️",
        "outcast": "🃏",
    }
    return emojis.get(role, "❓")


def get_player_list_text(players_dict, show_roles=False):
    lines = []
    for i, (uid, p) in enumerate(players_dict.items(), 1):
        status = "🟢" if p.alive else "💀"
        if show_roles:
            lines.append(f"{i}. {status} {p.name} - {ROLES[p.role]['name']}")
        else:
            lines.append(f"{i}. {status} {p.name}")
    return "\n".join(lines) if lines else "*ماكو لاعبين هسة*"


def assign_roles(num_players):
    """Assign roles based on number of players"""
    if num_players < 5:
        return None
    
    roles = []
    
    # Always have these
    roles.extend(["wolf", "seer", "healer"])
    
    if num_players >= 6:
        roles.append("wolf")
    if num_players >= 7:
        roles.append("lawyer")
    if num_players >= 8:
        roles.append("outcast")
    if num_players >= 9:
        roles.append("wolf")
    if num_players >= 10:
        roles.append("lawyer")
    if num_players >= 12:
        roles.append("wolf")
    if num_players >= 14:
        roles.append("wolf")
    if num_players >= 16:
        roles.append("seer")
    
    # Fill rest with civilians
    while len(roles) < num_players:
        roles.append("civilian")
    
    random.shuffle(roles)
    return roles


# ============================================================
# COMMAND HANDLERS
# ============================================================

async def announce_join(bot, game: GameSession, user):
    safe_name = html.escape(user.first_name or "لاعب")
    mention = f'<a href="tg://user?id={user.id}">{safe_name}</a>'
    await bot.send_message(
        chat_id=game.chat_id,
        text=f"🐺 أفلا انضم {mention} للعبة!",
        parse_mode="HTML"
    )


def add_player_to_game(game: GameSession, user):
    if user.id in game.players:
        return "already"
    if len(game.players) >= 20:
        return "full"
    game.players[user.id] = Player(user_id=user.id, name=user.first_name or "لاعب")
    user_games[user.id] = game.game_id
    return "joined"


async def join_from_deep_link(update: Update, context: ContextTypes.DEFAULT_TYPE, game_id: str):
    user = update.effective_user
    game = games.get(game_id)
    if not game or game.phase != GamePhase.WAITING:
        await update.message.reply_text("هاللعبة ما بقت مفتوحة يمعود.")
        return
    status = add_player_to_game(game, user)
    if status == "already":
        await update.message.reply_text("إنت داخل من قبل يمعود 😂")
        return
    if status == "full":
        await update.message.reply_text("اللعبة امتلت يمعود 😂")
        return
    chat_title = game.host_name
    try:
        chat = await context.bot.get_chat(game.chat_id)
        chat_title = chat.title or game.host_name
    except Exception:
        pass
    await update.message.reply_text(f"🐺 تم انضمامك بكروب «{chat_title}» بنجاح 😎")
    await announce_join(context.bot, game, user)


async def start_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle /start and private deep-link joining."""
    if context.args and context.args[0].startswith("join_"):
        game_id = context.args[0].split("_", 1)[1]
        await join_from_deep_link(update, context, game_id)
        return
    await update.message.reply_text(MSG["welcome"], parse_mode="Markdown")


async def newgame_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Create a new game session"""
    user = update.effective_user
    chat_id = update.effective_chat.id
    
    # Check if user already has an active game
    if user.id in user_games and user_games[user.id] in games:
        old_game = games[user_games[user.id]]
        if old_game.phase != GamePhase.ENDED:
            await update.message.reply_text(
                "يا {name}، عندك لعبة شغالة! إذا تريد تنهيها اكتب /endgame.".format(name=user.first_name)
            )
            return
    
    game_id = generate_game_id()
    game = GameSession(
        game_id=game_id,
        host_id=user.id,
        host_name=user.first_name,
        chat_id=chat_id
    )
    
    # Add host as first player
    game.players[user.id] = Player(
        user_id=user.id,
        name=user.first_name
    )
    
    games[game_id] = game
    user_games[user.id] = game_id

    for subscriber_id in list(nextgame_subscribers):
        try:
            await context.bot.send_message(chat_id=subscriber_id, text="🐺 يمعود، انفتحت لعبة جديدة! روح للكروب إذا تريد تلعب.")
        except Exception:
            pass
    nextgame_subscribers.clear()

    players_text = get_player_list_text(game.players)
    join_seconds = 60
    game.join_deadline = time.monotonic() + join_seconds
    bot_username = context.bot.username
    join_url = f"https://t.me/{bot_username}?start=join_{game_id}" if bot_username else None
    keyboard = InlineKeyboardMarkup([[InlineKeyboardButton("🚪 يلا دوس انضمام", url=join_url)]]) if join_url else None
    await update.message.reply_text(
        MSG["game_created"].format(
            host_name=user.first_name,
            game_id=game_id,
            count=len(game.players),
            max_players=20,
            players_list=players_text,
            seconds=join_seconds,
        ),
        parse_mode="Markdown",
        reply_markup=keyboard,
    )
    game.join_task = asyncio.create_task(join_timer(context.application, game_id))


async def join_timer(application: Application, game_id: str):
    while True:
        game = games.get(game_id)
        if not game or game.phase != GamePhase.WAITING or game.join_deadline is None:
            return
        remaining = game.join_deadline - time.monotonic()
        if remaining <= 0:
            await application.bot.send_message(
                chat_id=game.chat_id,
                text="⏰ خلص وقت الانضمام! صاحب اللعبة يگدر يبدي بـ /startgame إذا العدد صار 5 أو أكثر."
            )
            return
        await asyncio.sleep(min(remaining, 2))


async def extend_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user = update.effective_user
    game_id = user_games.get(user.id)
    game = games.get(game_id) if game_id else None
    if not game or game.phase != GamePhase.WAITING:
        await update.message.reply_text("ماكو جلسة مفتوحة هسة.")
        return
    if user.id != game.host_id:
        await update.message.reply_text("بس صاحب اللعبة يگدر يغيّر المهلة يمعود.")
        return
    if not context.args:
        await update.message.reply_text("اكتب مثل: /extend 30 حتى تزيد 30 ثانية، أو /extend -10 حتى تنقص 10 ثواني.")
        return
    try:
        delta = int(context.args[0])
    except ValueError:
        await update.message.reply_text("اكتب رقم صحيح يمعود، مثل /extend 30 أو /extend -10")
        return
    game.join_deadline = max(time.monotonic(), game.join_deadline + delta)
    remaining = max(0, int(game.join_deadline - time.monotonic()))
    if game.join_task is None or game.join_task.done():
        game.join_task = asyncio.create_task(join_timer(context.application, game.game_id))
    await update.message.reply_text(f"⏳ تم تعديل مهلة الانضمام. هسة باقي {remaining} ثانية.")


async def flee_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user = update.effective_user
    game_id = user_games.get(user.id)
    game = games.get(game_id) if game_id else None
    if not game or user.id not in game.players:
        await update.message.reply_text("إنت مو داخل بلعبة هسة يمعود.")
        return
    if game.phase != GamePhase.WAITING:
        await update.message.reply_text("ما تگدر تطلع بعد ما بدت اللعبة يمعود.")
        return
    if user.id == game.host_id:
        await update.message.reply_text("إنت صاحب اللعبة. إذا تريد توقفها استخدم /endgame.")
        return
    del game.players[user.id]
    user_games.pop(user.id, None)
    await update.message.reply_text("تمام، طلعت من اللعبة.")
    await context.bot.send_message(chat_id=game.chat_id, text=f"🚪 {user.first_name} طلع من الانتظار.")


async def nextgame_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    nextgame_subscribers.add(update.effective_user.id)
    await update.message.reply_text("تمام يمعود، من تنفتح لعبة جديدة أنبهك بالخاص إذا گدرت أوصلك.")


async def stats_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    st = player_stats.get(update.effective_user.id, {})
    text = (
        "📊 إحصائياتك:\n\n"
        f"🎮 لعبت: {st.get('games', 0)}\n"
        f"🏆 فوز: {st.get('wins', 0)}\n"
        f"💀 خسارة: {st.get('losses', 0)}\n"
        f"🗳️ أصوات: {st.get('votes', 0)}"
    )
    await update.message.reply_text(text)


async def ping_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    started = time.perf_counter()
    msg = await update.message.reply_text("🏓 دا أفحص السرعة...")
    ms = int((time.perf_counter() - started) * 1000)
    await msg.edit_text(f"🏓 حاضر يمعود! سرعة الرد تقريباً {ms}ms")


async def chatid_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(f"🆔 آيدي هالمكان: `{update.effective_chat.id}`", parse_mode="Markdown")


async def version_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("🐺 نسخة بوت مافية الذئب العراقية: 1.0")


async def runinfo_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    active = sum(1 for g in games.values() if g.phase != GamePhase.ENDED)
    await update.message.reply_text(
        f"🧠 البوت شغال تمام.\n🎮 ألعاب شغالة: {active}\n🐺 الجلسات المحفوظة: {len(games)}"
    )


async def getstatus_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("🟢 البوت شغال زين يمعود.")


async def config_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "⚙️ الإعدادات الحالية:\n"
        "👥 أقل عدد: 5\n"
        "👥 أكثر عدد: 20\n"
        "⏳ مهلة الانضمام: تتغير بـ /extend\n"
        "🗳️ التصويت: بالخاص وينعلن بالمجموعة"
    )


async def donate_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("❤️ ما نطلب منك فلوس يمعود، دعمك للبوت إنك تلعب وتستانس بس 😂")


async def grouplist_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    waiting = [g for g in games.values() if g.phase == GamePhase.WAITING]
    if not waiting:
        await update.message.reply_text("ماكو جلسات مفتوحة هسة.")
        return
    lines = [f"• كود {g.game_id} - {len(g.players)}/20 لاعب" for g in waiting]
    await update.message.reply_text("🎮 الجلسات المفتوحة هسة:\n" + "\n".join(lines))


async def startchaos_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    game_id = user_games.get(update.effective_user.id)
    game = games.get(game_id) if game_id else None
    if not game or update.effective_user.id != game.host_id:
        await update.message.reply_text("بس صاحب اللعبة يگدر يبدي وضع الفوضى.")
        return
    game.chaos_mode = True
    await update.message.reply_text("🌪️ يلا، فعلنا وضع الفوضى! هسة أبدي اللعبة.")
    await startgame_command(update, context)


async def forcestart_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await startgame_command(update, context)


async def smite_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("⚡ هالأمر مخصص لإدارة البوت وما مفعل هسة حتى ما يصير ظلم باللعب.")


async def uploadlang_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("🌐 نظام ملفات اللغات مو محتاجينه هسة، لأن البوت عراقي من الأساس 😂🇮🇶")


async def validatelangs_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("🇮🇶 اللغة مضبوطة: عراقي بالكامل.")


async def join_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Join an existing game"""
    user = update.effective_user
    
    # Find the most recent game
    if not games:
        await update.message.reply_text(MSG["no_game"])
        return
    
    # Get the latest non-ended game
    available_game = None
    for gid, g in games.items():
        if g.phase == GamePhase.WAITING:
            available_game = g
            break
    
    if not available_game:
        await update.message.reply_text(MSG["no_game"])
        return
    
    # Check if already joined
    if user.id in available_game.players:
        await update.message.reply_text(
            MSG["already_joined"].format(name=user.first_name)
        )
        return
    
    # Check if game is full
    if len(available_game.players) >= 20:
        await update.message.reply_text(MSG["game_full"])
        return
    
    # Add player
    available_game.players[user.id] = Player(
        user_id=user.id,
        name=user.first_name
    )
    user_games[user.id] = available_game.game_id
    
    players_text = get_player_list_text(available_game.players)
    
    hint = ""
    if len(available_game.players) >= 5:
        hint = f"✅ العدد صار كافي! صاحب اللعبة يگدر يبدي بـ /startgame"
    else:
        remaining = 5 - len(available_game.players)
        hint = f"⏳ بعد ناقص {remaining} حتى نبدي"
    
    await update.message.reply_text(
        MSG["joined"].format(
            name=user.first_name,
            count=len(available_game.players),
            max=20,
            players_list=players_text,
            hint=hint
        ),
        parse_mode="Markdown"
    )


async def players_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Show current players"""
    user = update.effective_user
    
    if user.id not in user_games or user_games[user.id] not in games:
        await update.message.reply_text(MSG["no_game"])
        return
    
    game = games[user_games[user.id]]
    show_roles = game.phase == GamePhase.ENDED
    players_text = get_player_list_text(game.players, show_roles=show_roles)
    
    phase_text = {
        GamePhase.WAITING: "⏳ ننتظر",
        GamePhase.NIGHT: "🌙 ليل",
        GamePhase.MORNING: "☀️ صبح",
        GamePhase.DISCUSSION: "💬 حچي",
        GamePhase.VOTING: "🗳️ تصويت",
        GamePhase.ENDED: "🏁 خلصت",
    }.get(game.phase, "❓")
    
    await update.message.reply_text(
        f"🎮 *مافية الذئب - اللاعبين*\n\n"
        f"📊 هسة: {phase_text}\n"
        f"🔄 الجولة: {game.round_num}\n\n"
        f"{players_text}",
        parse_mode="Markdown"
    )


async def startgame_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Start the game (host only)"""
    user = update.effective_user
    
    if user.id not in user_games or user_games[user.id] not in games:
        await update.message.reply_text(MSG["no_game"])
        return
    
    game = games[user_games[user.id]]
    
    # Check if host
    if user.id != game.host_id:
        await update.message.reply_text(MSG["not_host"].format(name=user.first_name))
        return
    
    # Check minimum players
    if len(game.players) < 5:
        await update.message.reply_text(
            f"⛔ بعد ناقص لاعبين! نحتاج 5، وإنتو هسة {len(game.players)}"
        )
        return
    
    # سجّل بداية اللعبة بالإحصائيات
    for _uid in game.players:
        player_stats.setdefault(_uid, {"games": 0, "wins": 0, "losses": 0, "votes": 0})["games"] += 1

    # Assign roles
    roles = assign_roles(len(game.players))
    if not roles:
        await update.message.reply_text("صار لخبطه بتوزيع الأدوار، جرّب مرة ثانية.")
        return
    
    for i, (uid, player) in enumerate(game.players.items()):
        player.role = roles[i]
        player.team = ROLES[roles[i]]["team"]
    
    # Start the game
    game.phase = GamePhase.NIGHT
    game.round_num = 1
    
    # بداية اللعبة: فيديو القمر فقط، بدون حريق أو سكين.
    await send_effect(
        context.bot,
        update.effective_chat.id,
        EVENT_EFFECTS["game_start"],
        "🌙 عصام @eia_qw"
    )
    await update.message.reply_text("🐺 *عصام @eia_qw*", parse_mode="Markdown")
    await update.message.reply_text(MSG["game_starting"], parse_mode="Markdown")
    
    # Send roles to each player via PM
    bot = context.bot
    for uid, player in game.players.items():
        role_info = ROLES[player.role]
        try:
            await bot.send_message(
                chat_id=uid,
                text=MSG["role_assigned"].format(
                    role_name=role_info["name"],
                    role_description=role_info["description"],
                    abilities=f"*قدراتك:*\n{role_info['abilities']}"
                ),
                parse_mode="Markdown"
            )
        except Exception as e:
            logger.warning(f"Could not PM role to {uid}: {e}")
            # If can't PM, announce in group (less ideal but works)
            pass
    
    # Start night phase
    await asyncio.sleep(3)
    await night_phase(update, context, game)


async def night_phase(update: Update, context: ContextTypes.DEFAULT_TYPE, game: GameSession):
    """Handle the night phase"""
    game.phase = GamePhase.HEALER
    game.night_kills = []
    chat_id = update.effective_chat.id
    await send_random_effect(context.bot, chat_id, ["night_wolf.mp4", "night_wolf_alt.mp4"], "🌙 حل الليل... الذئاب گعدت!")
    for p in game.players.values():
        if hasattr(p, "_vote_target"):
            delattr(p, "_vote_target")
    
    # Reset protections
    for p in game.players.values():
        p.protected_by_healer = False
    
    bot = context.bot
    chat_id = update.effective_chat.id
    
    # Phase 1: Healer protects
    healers = [(uid, p) for uid, p in game.players.items() if p.role == "healer" and p.alive]
    if healers:
        for uid, healer in healers:
            targets = [(tid, t.name) for tid, t in game.players.items() if t.alive]
            keyboard = [[InlineKeyboardButton(t_name, callback_data=f"heal_{tid}")] for tid, t_name in targets]
            reply_markup = InlineKeyboardMarkup(keyboard)
            
            try:
                await bot.send_message(
                    chat_id=uid,
                    text=MSG["healer_prompt"].format(
                        targets="\n".join([f"- {t_name}" for _, t_name in targets])
                    ),
                    reply_markup=reply_markup,
                    parse_mode="Markdown"
                )
            except:
                pass
    
    await asyncio.sleep(15)
    
    # Phase 2: Seer investigates
    game.phase = GamePhase.SEER
    seers = [(uid, p) for uid, p in game.players.items() if p.role == "seer" and p.alive]
    if seers:
        for uid, seer in seers:
            targets = [(tid, t.name) for tid, t in game.players.items() if t.alive and tid != uid]
            keyboard = [[InlineKeyboardButton(t_name, callback_data=f"seer_{tid}")] for tid, t_name in targets]
            reply_markup = InlineKeyboardMarkup(keyboard)
            
            try:
                await bot.send_message(
                    chat_id=uid,
                    text=MSG["seer_prompt"].format(
                        targets="\n".join([f"- {t_name}" for _, t_name in targets])
                    ),
                    reply_markup=reply_markup,
                    parse_mode="Markdown"
                )
            except:
                pass
    
    await asyncio.sleep(15)
    
    # Phase 3: Wolves vote
    game.phase = GamePhase.WOLF
    wolves = [(uid, p) for uid, p in game.players.items() if p.role == "wolf" and p.alive]
    alive_civilians = [(uid, p) for uid, p in game.players.items() if p.alive and p.role != "wolf"]
    
    if wolves and alive_civilians:
        wolf_names = ", ".join([p.name for _, p in wolves])
        
        for uid, wolf in wolves:
            targets = [(tid, t.name) for tid, t in alive_civilians]
            keyboard = [[InlineKeyboardButton(t_name, callback_data=f"kill_{tid}")] for tid, t_name in targets]
            reply_markup = InlineKeyboardMarkup(keyboard)
            
            try:
                await bot.send_message(
                    chat_id=uid,
                    text=MSG["wolf_prompt"].format(
                        targets="\n".join([f"- {t_name}" for _, t_name in targets]),
                        timer_warning="⏰ عندك 30 ثانية، لا تطوّل 😂"
                    ),
                    reply_markup=reply_markup,
                    parse_mode="Markdown"
                )
            except:
                pass
    
    await asyncio.sleep(30)
    
    # Process night results
    await process_night_results(update, context, game)


async def process_night_results(update: Update, context: ContextTypes.DEFAULT_TYPE, game: GameSession):
    """Process the results of the night phase"""
    bot = context.bot
    chat_id = update.effective_chat.id
    
    # Count wolf votes
    wolf_votes = {}
    for uid, player in game.players.items():
        if player.role == "wolf" and player.alive and hasattr(player, '_vote_target'):
            target = player._vote_target
            wolf_votes[target] = wolf_votes.get(target, 0) + 1
    
    # Pick the target with most votes
    if wolf_votes:
        max_votes = max(wolf_votes.values())
        top_targets = [t for t, v in wolf_votes.items() if v == max_votes]
        chosen_target = random.choice(top_targets)
        
        target_player = game.players.get(chosen_target)
        if target_player and target_player.alive:
            if not target_player.protected_by_healer:
                target_player.alive = False
                game.night_kills.append(chosen_target)
                await send_effect(
                    bot, chosen_target, "wolf_attack.mp4",
                    "🐺 الذيب هجم عليك الليلة... خلاص طلعت 😂"
                )
                
                cause = random.choice([
                    "انبلع بالليل! 😱",
                    "الذئاب بلعته! 💀",
                    "الذئاب أكلته! 🩸",
                ])
                
                death_msg = MSG["death_announcement"].format(
                    name=target_player.name,
                    role=ROLES[target_player.role]["name"],
                    cause=cause
                )
            else:
                death_msg = MSG["morning_arrives"].format(
                    death_message=f"☀️ *الصبح صار!* \n\nالحمدلله! {target_player.name} نجا بفضل الحكيم! 🛡️",
                    alive_count=sum(1 for p in game.players.values() if p.alive),
                    alive_list=get_player_list_text({k: v for k, v in game.players.items() if v.alive}),
                    discussion_prompt="💬 *هسة وقت الحچي!* منو تشكون بيه؟"
                )
    else:
        # No votes, random target
        alive_non_wolves = [uid for uid, p in game.players.items() if p.alive and p.role != "wolf"]
        if alive_non_wolves:
            chosen = random.choice(alive_non_wolves)
            target_player = game.players[chosen]
            if not target_player.protected_by_healer:
                target_player.alive = False
                game.night_kills.append(chosen)
                await send_effect(
                    bot, chosen, "wolf_attack.mp4",
                    "🐺 الذيب هجم عليك الليلة... خلاص طلعت 😂"
                )
                death_msg = MSG["death_announcement"].format(
                    name=target_player.name,
                    role=ROLES[target_player.role]["name"],
                    cause="انبلع بالليل! 😱"
                )
            else:
                death_msg = None
        else:
            death_msg = None
    
    # Announce morning
    if death_msg:
        try:
            await bot.send_message(
                chat_id=chat_id,
                text=MSG["morning_arrives"].format(
                    death_message=death_msg,
                    alive_count=sum(1 for p in game.players.values() if p.alive),
                    alive_list=get_player_list_text({k: v for k, v in game.players.items() if v.alive}),
                    discussion_prompt="💬 *هسة وقت الحچي!* منو تشكون بيه؟"
                ),
                parse_mode="Markdown"
            )
        except:
            pass
    else:
        try:
            await bot.send_message(
                chat_id=chat_id,
                text=MSG["no_death"].format(
                    alive_count=sum(1 for p in game.players.values() if p.alive),
                    alive_list=get_player_list_text({k: v for k, v in game.players.items() if v.alive})
                ),
                parse_mode="Markdown"
            )
        except:
            pass
    
    # Check win condition
    if await check_win(update, context, game):
        return
    
    # Move to discussion
    await discussion_phase(update, context, game)


async def discussion_phase(update: Update, context: ContextTypes.DEFAULT_TYPE, game: GameSession):
    """Handle the discussion phase"""
    game.phase = GamePhase.DISCUSSION
    chat_id = update.effective_chat.id
    
    await context.bot.send_message(
        chat_id=chat_id,
        text=MSG["discussion_time"].format(seconds=60),
        parse_mode="Markdown"
    )
    
    await asyncio.sleep(60)
    
    # Move to voting
    await voting_phase(update, context, game)


async def voting_phase(update: Update, context: ContextTypes.DEFAULT_TYPE, game: GameSession):
    """Handle the voting phase"""
    game.phase = GamePhase.VOTING
    game.votes = {}
    chat_id = update.effective_chat.id

    for p in game.players.values():
        if hasattr(p, "_protect_target"):
            delattr(p, "_protect_target")

    lawyers = [(uid, p) for uid, p in game.players.items() if p.role == "lawyer" and p.alive and not p.has_used_lawyer]
    alive_players_for_lawyer = [(uid, p.name) for uid, p in game.players.items() if p.alive]
    for uid, lawyer in lawyers:
        keyboard = [[InlineKeyboardButton(name, callback_data=f"lawyer_{tid}")] for tid, name in alive_players_for_lawyer if tid != uid]
        try:
            await context.bot.send_message(chat_id=uid, text="⚖️ اختار واحد تدافع عنه إذا صار عليه أعلى أصوات (مرة وحدة بس):", reply_markup=InlineKeyboardMarkup(keyboard))
        except Exception as e:
            logger.warning("Could not PM lawyer %s: %s", uid, e)
    
    alive_players = [(uid, p.name) for uid, p in game.players.items() if p.alive]
    
    keyboard = [[InlineKeyboardButton(name, callback_data=f"vote_{uid}")] for uid, name in alive_players]
    keyboard.append([InlineKeyboardButton("🚫 أسحب هالمرة", callback_data="vote_skip")])
    reply_markup = InlineKeyboardMarkup(keyboard)

    await context.bot.send_message(
        chat_id=chat_id,
        text=MSG["voting_time"],
        parse_mode="Markdown"
    )

    # التصويت ينعمل بالخاص، وكل صوت ينعلن فوراً بالمجموعة.
    for uid, name in alive_players:
        try:
            await context.bot.send_message(
                chat_id=uid,
                text=MSG["vote_private"],
                reply_markup=reply_markup
            )
        except Exception as e:
            logger.warning("Could not send private voting keyboard to %s: %s", uid, e)
            await context.bot.send_message(
                chat_id=chat_id,
                text=f"⚠️ ما گدرت أوصل التصويت بالخاص لـ {name}. لازم يفتح خاص البوت ويكتب /start."
            )

    await asyncio.sleep(60)
    
    # Process votes
    await process_votes(update, context, game)


async def process_votes(update: Update, context: ContextTypes.DEFAULT_TYPE, game: GameSession):
    """Process voting results"""
    chat_id = update.effective_chat.id
    
    if not game.votes:
        await context.bot.send_message(
            chat_id=chat_id,
            text="🤷 ماكو أصوات، نروح لليل الجاي...",
            parse_mode="Markdown"
        )
        # Next night
        await night_phase(update, context, game)
        return
    
    # Count votes
    vote_counts = {}
    for voter, target in game.votes.items():
        if target == "skip":
            continue
        vote_counts[target] = vote_counts.get(target, 0) + 1
    
    if not vote_counts:
        await context.bot.send_message(
            chat_id=chat_id,
            text="🤷 الكل سحب، نروح لليل الجاي...",
            parse_mode="Markdown"
        )
        await night_phase(update, context, game)
        return
    
    max_votes = max(vote_counts.values())
    top_voted = [t for t, v in vote_counts.items() if v == max_votes]
    
    if len(top_voted) > 1:
        # Tie
        names = ", ".join([game.players.get(int(tid), Player(0, "Unknown")).name for tid in top_voted])
        await context.bot.send_message(
            chat_id=chat_id,
            text=MSG["tie_vote"].format(names=names),
            parse_mode="Markdown"
        )
        # Next night without elimination
        await night_phase(update, context, game)
        return
    
    # Eliminate the top voted
    eliminated_id = int(top_voted[0])
    eliminated = game.players.get(eliminated_id)
    
    if eliminated:
        lawyers = [p for p in game.players.values() if p.role == "lawyer" and p.alive and not p.has_used_lawyer]
        defender = next(
            (lawyer for lawyer in lawyers
             if hasattr(lawyer, "_protect_target") and lawyer._protect_target == eliminated_id),
            None
        )
        if defender:
            defender.has_used_lawyer = True
            await context.bot.send_message(
                chat_id=chat_id,
                text=f"⚖️ *المحامي دافع عن {eliminated.name}!*\n\nهالمرة ما راح يطلع 😎",
                parse_mode="Markdown"
            )
            await send_effect(context.bot, defender.user_id, "lawyer_defense.mp4", f"⚖️ دفاعك نجح وأنقذت {eliminated.name}!")
            await send_effect(context.bot, eliminated_id, "lawyer_defense.mp4", "🛡️ المحامي أنقذك من الطرد!")
            game.round_num += 1
            await night_phase(update, context, game)
            return

        eliminated.alive = False

        comments = [
            "خلصت سالفتك يمعود 😂",
            "يلا الله وياك 😂",
            "والله چنت شاك بيك 😂",
        ]
        
        # فيديو السكين مخصص للسفاح فقط، لذلك ما نستخدمه بالإقصاء العادي.
        await context.bot.send_message(
            chat_id=chat_id,
            text=MSG["elimination_result"].format(
                accused_name=eliminated.name,
                eliminated_message=MSG["player_eliminated"].format(
                    name=eliminated.name,
                    role=ROLES[eliminated.role]["name"],
                    comment=random.choice(comments)
                )
            ),
            parse_mode="Markdown"
        )
    
    # Check win condition
    if await check_win(update, context, game):
        return
    
    # Next round - night
    game.round_num += 1
    await night_phase(update, context, game)


async def check_win(update: Update, context: ContextTypes.DEFAULT_TYPE, game: GameSession) -> bool:
    """Check if any team has won"""
    chat_id = update.effective_chat.id
    
    alive_wolves = [p for p in game.players.values() if p.alive and p.team == "wolves"]
    alive_village = [p for p in game.players.values() if p.alive and p.team == "village"]
    alive_outcast = [p for p in game.players.values() if p.alive and p.team == "outcast"]
    
    wolves_win = len(alive_wolves) >= len(alive_village) and len(alive_village) > 0
    village_win = len(alive_wolves) == 0
    outcast_win = len(alive_outcast) > 0 and len(alive_outcast) == sum(1 for p in game.players.values() if p.alive)
    
    if wolves_win:
        wolves_list = "\n".join([f"🐺 {p.name}" for p in game.players.values() if p.role == "wolf"])
        await context.bot.send_message(
            chat_id=chat_id,
            text=MSG["wolves_win"].format(
                wolves_list=wolves_list,
                taunt=get_random_taunt(MSG["wolf_taunts"])
            ),
            parse_mode="Markdown"
        )
        await send_random_effect(context.bot, chat_id, ["wolf_victory.mp4", "wolf_victory_alt.mp4"], "🐺🩸 الذئاب فازوا!")
        game.phase = GamePhase.ENDED
        return True
    
    if village_win:
        survivors = [p for p in game.players.values() if p.alive]
        survivors_list = "\n".join([f"🛡️ {p.name}" for p in survivors])
        await context.bot.send_message(
            chat_id=chat_id,
            text=MSG["village_win"].format(
                survivors_list=survivors_list,
                celebration=get_random_taunt(MSG["village_celebrations"])
            ),
            parse_mode="Markdown"
        )
        await send_effect(context.bot, chat_id, "village_win.mp4", "🏆🎉 أهل القرية فازوا!")
        game.phase = GamePhase.ENDED
        return True
    
    if outcast_win:
        outcast_name = alive_outcast[0].name
        await context.bot.send_message(
            chat_id=chat_id,
            text=MSG["outcast_win"].format(name=outcast_name),
            parse_mode="Markdown"
        )
        await send_effect(context.bot, chat_id, "outcast_win.mp4", f"🃏 {outcast_name} فاز وحده!")
        game.phase = GamePhase.ENDED
        return True
    
    return False


async def endgame_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """End the current game"""
    user = update.effective_user
    
    if user.id not in user_games or user_games[user.id] not in games:
        await update.message.reply_text(MSG["no_game"])
        return
    
    game = games[user_games[user.id]]
    
    if user.id != game.host_id:
        await update.message.reply_text(MSG["not_host"].format(name=user.first_name))
        return
    
    game.phase = GamePhase.ENDED
    await update.message.reply_text(MSG["game_ended"])


async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Show help message"""
    await update.message.reply_text(MSG["help"], parse_mode="Markdown")


async def rules_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Show game rules"""
    await update.message.reply_text(MSG["rules"], parse_mode="Markdown")


# ============================================================
# CALLBACK HANDLERS
# ============================================================

async def button_callback(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle inline buttons with strict phase/role validation."""
    query = update.callback_query
    await query.answer()
    user = update.effective_user
    data = query.data or ""

    if user.id not in user_games or user_games[user.id] not in games:
        await query.edit_message_text("ماكو لعبة شغالة!")
        return

    game = games[user_games[user.id]]
    player = game.players.get(user.id)
    if not player:
        await query.edit_message_text("إنت مو داخل بهاللعبة!")
        return
    if not player.alive:
        await query.answer("إنت ميت يمعود، ما تگدر تسوي شي هسة 😂", show_alert=True)
        return

    if data.startswith("heal_"):
        if player.role != "healer" or game.phase != GamePhase.HEALER:
            await query.answer("هسة مو دور الحكيم.", show_alert=True)
            return
        target_id = int(data.split("_", 1)[1])
        target = game.players.get(target_id)
        if not target or not target.alive:
            await query.answer("هذا اللاعب ما تگدر تختاره هسة.", show_alert=True)
            return
        if target_id == user.id and game.last_protected == user.id:
            await query.answer("ما تگدر تحمي نفسك ليلتين ورا بعض يمعود.", show_alert=True)
            return
        for p in game.players.values():
            p.protected_by_healer = False
        target.protected_by_healer = True
        game.last_protected = target_id
        await query.edit_message_text(f"✅ حميت {target.name} هالليلة! 🛡️")
        await send_effect(context.bot, user.id, "healer_save.mp4", f"🛡️ حميت {target.name} بنجاح!")

    elif data.startswith("seer_"):
        if player.role != "seer" or game.phase != GamePhase.SEER:
            await query.answer("هسة مو دور العرّاف.", show_alert=True)
            return
        target_id = int(data.split("_", 1)[1])
        target = game.players.get(target_id)
        if not target or not target.alive or target_id == user.id:
            await query.answer("هذا اللاعب ما تگدر تختاره هسة.", show_alert=True)
            return
        result = "🐺 *ذيب!*" if target.role == "wolf" else "🛡️ *مو ذيب*"
        comments = [
            "صح عليك! كشفته 😂👁️",
            "هاي النتيجة، لا تفضح روحك 😂🤫",
            "خوش كشف يمعود 😂",
        ]
        await query.edit_message_text(
            MSG["seer_result"].format(name=target.name, result=result, comment=random.choice(comments)),
            parse_mode="Markdown"
        )
        await send_effect(context.bot, user.id, "seer_check.mp4", f"🔮 نتيجة الكشف: {target.name}")

    elif data.startswith("kill_"):
        if player.role != "wolf" or game.phase != GamePhase.WOLF:
            await query.answer("هسة مو دور الذيب.", show_alert=True)
            return
        target_id = int(data.split("_", 1)[1])
        target = game.players.get(target_id)
        if not target or not target.alive or target.role == "wolf":
            await query.answer("ما تگدر تختار هذا يمعود.", show_alert=True)
            return
        player._vote_target = target_id
        await query.edit_message_text(f"✅ اخترت {target.name}، خوش اختيار 😂🐺")

    elif data.startswith("lawyer_"):
        if player.role != "lawyer" or game.phase != GamePhase.VOTING:
            await query.answer("هسة مو دور المحامي.", show_alert=True)
            return
        if player.has_used_lawyer:
            await query.answer("دفاعك مستعمله من قبل يمعود.", show_alert=True)
            return
        target_id = int(data.split("_", 1)[1])
        target = game.players.get(target_id)
        if not target or not target.alive:
            await query.answer("هذا اللاعب ما تگدر تختاره هسة.", show_alert=True)
            return
        player._protect_target = target_id
        await query.edit_message_text(f"⚖️ اخترت تدافع عن {target.name} إذا طلع بالتصويت.")
        await send_effect(context.bot, user.id, "lawyer_defense.mp4", f"⚖️ جهزت دفاعك عن {target.name}!")

    elif data.startswith("vote_"):
        if game.phase != GamePhase.VOTING:
            await query.answer("هسة مو وقت التصويت يمعود.", show_alert=True)
            return
        if data == "vote_skip":
            if user.id in game.votes:
                await query.answer("إنت مصوّت من قبل.", show_alert=True)
                return
            game.votes[user.id] = "skip"
            await query.edit_message_text("🚫 قررت تسحب هالمرة.")
            return
        target_id = int(data.split("_", 1)[1])
        target = game.players.get(target_id)
        if not target or not target.alive:
            await query.answer("هذا اللاعب ما تگدر تختاره هسة.", show_alert=True)
            return
        if user.id in game.votes:
            await query.answer("إنت مصوّت من قبل يمعود 😂", show_alert=True)
            return
        game.votes[user.id] = target_id
        player_stats.setdefault(user.id, {"games": 0, "wins": 0, "losses": 0, "votes": 0})["votes"] += 1
        await query.edit_message_text(MSG["vote_cast"])

        # الإعلان ينرسل فوراً بالمجموعة ويكون ويا منشن للطرفين، بدون قائمة مصوتين بالنهاية.
        voter_name = html.escape(player.name)
        target_name = html.escape(target.name)
        voter_mention = f'<a href="tg://user?id={user.id}">{voter_name}</a>'
        target_mention = f'<a href="tg://user?id={target.user_id}">{target_name}</a>'
        await context.bot.send_message(
            chat_id=game.chat_id,
            text=f"🗳️ {voter_mention} صوّت على {target_mention}",
            parse_mode="HTML"
        )


# ============================================================
# MAIN
# ============================================================

async def setup_commands(application: Application):
    """Set up bot commands menu"""
    commands = [
        BotCommand("start", "شغّل البوت"),
        BotCommand("newgame", "سوّي جلسة جديدة"),
        BotCommand("startgame", "ابدأ اللعب"),
        BotCommand("startchaos", "ابدأ الفوضى"),
        BotCommand("extend", "غيّر مهلة الانضمام"),
        BotCommand("players", "شوف اللاعبين"),
        BotCommand("flee", "اطلع من اللعبة"),
        BotCommand("nextgame", "نبهني للجولة الجاية"),
        BotCommand("stats", "إحصائياتك"),
        BotCommand("ping", "افحص سرعة البوت"),
        BotCommand("chatid", "طلع آيدي المكان"),
        BotCommand("version", "نسخة البوت"),
        BotCommand("runinfo", "معلومات التشغيل"),
        BotCommand("getstatus", "حالة البوت"),
        BotCommand("config", "إعدادات الجلسة"),
        BotCommand("forcestart", "ابدأ بالقوة"),
        BotCommand("donate", "دعم البوت بدون فلوس 😂"),
        BotCommand("grouplist", "الجلسات المفتوحة"),
        BotCommand("smite", "أمر إدارة"),
        BotCommand("uploadlang", "أمر إدارة اللغة"),
        BotCommand("validatelangs", "تدقيق اللغة"),
        BotCommand("endgame", "خلص اللعبة"),
        BotCommand("rules", "قوانين اللعب"),
        BotCommand("help", "شنو تسوي؟"),
    ]
    await application.bot.set_my_commands(commands)

def main():
    """Run the bot"""
    token = TOKEN
    if not token:
        raise RuntimeError("BOT_TOKEN is not set. Put it in the server environment; do not hard-code it in source code.")
    
    application = Application.builder().token(token).build()
    
    # Command handlers
    application.add_handler(CommandHandler("start", start_command))
    application.add_handler(CommandHandler("newgame", newgame_command))
    application.add_handler(CommandHandler("players", players_command))
    application.add_handler(CommandHandler("startgame", startgame_command))
    application.add_handler(CommandHandler("startchaos", startchaos_command))
    application.add_handler(CommandHandler("extend", extend_command))
    application.add_handler(CommandHandler("flee", flee_command))
    application.add_handler(CommandHandler("nextgame", nextgame_command))
    application.add_handler(CommandHandler("stats", stats_command))
    application.add_handler(CommandHandler("ping", ping_command))
    application.add_handler(CommandHandler("chatid", chatid_command))
    application.add_handler(CommandHandler("version", version_command))
    application.add_handler(CommandHandler("runinfo", runinfo_command))
    application.add_handler(CommandHandler("getstatus", getstatus_command))
    application.add_handler(CommandHandler("config", config_command))
    application.add_handler(CommandHandler("forcestart", forcestart_command))
    application.add_handler(CommandHandler("donate", donate_command))
    application.add_handler(CommandHandler("grouplist", grouplist_command))
    application.add_handler(CommandHandler("smite", smite_command))
    application.add_handler(CommandHandler("uploadlang", uploadlang_command))
    application.add_handler(CommandHandler("validatelangs", validatelangs_command))
    application.add_handler(CommandHandler("endgame", endgame_command))
    application.add_handler(CommandHandler("help", help_command))
    application.add_handler(CommandHandler("rules", rules_command))
    
    # Callback handler
    application.add_handler(CallbackQueryHandler(button_callback))
    
    # Post-init
    application.post_init = setup_commands
    
    print("🐺 بوت مافية الذئب شغال! يلا العبوا!")
    application.run_polling(allowed_updates=Update.ALL_TYPES)


if __name__ == "__main__":
    main()
